using System.Collections.Immutable;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using MinorShift.Emuera.Next.Compiler;
using MinorShift.Emuera.Next.Core;
using MinorShift.Emuera.Next.Vm;

if (args.Length < 2) { Console.Error.WriteLine("Usage: Emuera.Next.VmAudit <fixture-root> <report-directory> [legacy-manifest.jsonl] [phase1-compiler-manifest.jsonl]"); return 2; }
var auditWatch = Stopwatch.StartNew(); var fixtureRoot = Path.GetFullPath(args[0]);
var erbRoot = Directory.Exists(Path.Combine(fixtureRoot, "Data", "ERB")) ? Path.Combine(fixtureRoot, "Data", "ERB") : fixtureRoot;
var report = Path.GetFullPath(args[1]); Directory.CreateDirectory(report); var legacyPath = args.Length > 2 ? Path.GetFullPath(args[2]) : null; var phase1Path = args.Length > 3 ? Path.GetFullPath(args[3]) : null;
var indexWatch = Stopwatch.StartNew(); var files = ErbSourceIndexer.IndexDirectory(erbRoot); indexWatch.Stop();
var oracleWatch = Stopwatch.StartNew(); var legacy = legacyPath is null ? new LegacyOracle([], new()) : ReadLegacy(legacyPath); oracleWatch.Stop(); var overlay = legacy.Overlay;
var sourceRows = files.SelectMany((file, fileOrdinal) => file.Functions.Select((function, functionOrdinal) => new SourceRow(NormalizeRelative(Path.GetRelativePath(erbRoot, file.FileIdentity)), functionOrdinal, function.Span.StartLine, function.Name, fileOrdinal, function.Flags))).ToArray();
var sourceKeys = sourceRows.Select(x => new SemanticFunctionKey(x.RelativeFile, x.FunctionOrdinal)).ToHashSet(); var legacyByKey = legacy.Rows.ToDictionary(x => new SemanticFunctionKey(x.RelativeFile, x.FunctionOrdinal));
var identityMissingRows = sourceRows.Where(x => !legacyByKey.ContainsKey(new(x.RelativeFile, x.FunctionOrdinal))).ToArray(); var identityExtraRows = legacy.Rows.Where(x => !sourceKeys.Contains(new(x.RelativeFile, x.FunctionOrdinal))).ToArray();
var sourcePositionKeys = sourceRows.Select(x => $"{x.RelativeFile}:{x.StartLine}").ToHashSet(StringComparer.OrdinalIgnoreCase); var sourceByOrdinal = sourceRows.ToDictionary(x => new SemanticFunctionKey(x.RelativeFile, x.FunctionOrdinal));
var positionResidualRows = legacy.Rows.Where(x => !sourcePositionKeys.Contains($"{x.RelativeFile}:{x.StartLine}")).Select(x => { var hasSource = sourceByOrdinal.TryGetValue(new(x.RelativeFile, x.FunctionOrdinal), out var source); return new PositionResidual(x.RelativeFile, x.FunctionOrdinal, hasSource ? source.FunctionOrdinal : -1, x.StartLine, hasSource ? source.StartLine : -1, hasSource ? source.PhysicalName : "<no SourceIndex definition>", x.FunctionName); }).ToArray();
var exactPhysicalStartLineMatch = legacy.Rows.Count(x => sourcePositionKeys.Contains($"{x.RelativeFile}:{x.StartLine}"));
var catalogWatch = Stopwatch.StartNew(); var catalog = FunctionCatalog.FromSourceIndex(files, erbRoot, overlay, true); catalogWatch.Stop();

var phase1Keys = phase1Path is null ? null : ReadPhase1Keys(phase1Path); var compiler = new FunctionCompiler(CompilerCompatibilityOptions.LegacyDefaults); var prototypes = new List<FunctionPrototype>(sourceRows.Length); var compiledIds = new List<int>(); var excluded = new List<string>();
var instructionCount = 0; var compileErrors = 0; var phase1Matches = 0; var compileWatch = Stopwatch.StartNew(); var functionId = 0;
foreach (var file in files)
{
    if (file.HasFallback) { functionId += file.Functions.Count; continue; }
    using var session = FunctionSourceReader.OpenFile(file);
    foreach (var function in file.Functions)
    {
        var id = functionId++; var key = Key(erbRoot, file.FileIdentity, function.Span.StartLine); if (function.Flags != SourceIndexFlags.None) continue;
        if (phase1Keys is not null && !phase1Keys.Contains(key)) { excluded.Add($"{key}\t{function.Name}"); continue; } if (phase1Keys is not null) phase1Matches++;
        var read = session.Read(function); if (read.Status != SourceReadStatus.Read) { compileErrors++; continue; } var result = compiler.TryCompile(read.Source!.Value); if (result.Status != CompileStatus.Compiled) { compileErrors++; continue; }
        var compiled = result.Function!; var bytes = read.Source.Value.Bytes; var operands = compiled.Instructions.Select(i => i.OperandLength == 0 ? string.Empty : Encoding.UTF8.GetString(bytes, i.OperandOffset, i.OperandLength)).ToImmutableArray(); prototypes.Add(new(id, compiled.Instructions, operands)); compiledIds.Add(id); instructionCount += compiled.Instructions.Length;
    }
}
compileWatch.Stop(); catalog.MarkCodeAvailable(compiledIds); var linkWatch = Stopwatch.StartNew(); var link = ControlLinker.Link(catalog, prototypes); linkWatch.Stop();

var structureCodes = new[] { PrototypeOpcode.SIF, PrototypeOpcode.IF, PrototypeOpcode.ELSEIF, PrototypeOpcode.ELSE, PrototypeOpcode.ENDIF, PrototypeOpcode.SELECTCASE, PrototypeOpcode.CASE, PrototypeOpcode.CASEELSE, PrototypeOpcode.ENDSELECT, PrototypeOpcode.REPEAT, PrototypeOpcode.REND, PrototypeOpcode.FOR, PrototypeOpcode.NEXT, PrototypeOpcode.WHILE, PrototypeOpcode.WEND, PrototypeOpcode.DO, PrototypeOpcode.LOOP, PrototypeOpcode.BREAK, PrototypeOpcode.CONTINUE }; var allInstructions = prototypes.SelectMany(x => x.Instructions).ToArray(); var structureCounts = allInstructions.Where(x => structureCodes.Contains(x.Opcode)).GroupBy(x => x.Opcode.ToString()).ToDictionary(x => x.Key, x => x.Count()); var ids = Enumerable.Range(0, catalog.Count).ToArray();
var effectiveGroups = ids.Where(id => catalog[id].EffectiveNameKnown).GroupBy(id => catalog.GetEffectiveName(id)!, StringComparer.OrdinalIgnoreCase).Where(x => x.Count() > 1).ToArray(); var physicalGroups = ids.GroupBy(catalog.GetPhysicalName, StringComparer.OrdinalIgnoreCase).Where(x => x.Count() > 1).ToArray();
var spanMismatch = CompareSpans(prototypes, link.Program); var localPcErrors = VerifyLocalPcs(link.Program); var implicitCandidates = prototypes.Count(x => !x.Instructions.Any(i => i.Opcode is PrototypeOpcode.RETURN or PrototypeOpcode.RETURNFORM or PrototypeOpcode.RETURNF)); var codeAvailable = ids.Count(id => catalog[id].CodeAvailable); var linkReady = link.Program.Descriptors.Count(x => x.State == VmFunctionState.LinkReady); var pending = link.Program.Descriptors.Count(x => x.State == VmFunctionState.LinkedSemanticPending); var executableReal = link.Program.Descriptors.Count(x => x.State == VmFunctionState.ExecutableReady);
var maxDepth = link.Program.StructuralLinks.Length == 0 ? 0 : link.Program.StructuralLinks.Max(x => x.Depth); var maxFunctionInstructions = prototypes.Count == 0 ? 0 : prototypes.Max(x => x.Instructions.Length); var instructionPayload = (long)link.Program.Code.Length * Marshal.SizeOf<VmInstruction>(); var descriptorPayload = (long)link.Program.Descriptors.Length * Marshal.SizeOf<VmFunctionDescriptor>(); var recordPayload = (long)link.Program.StructuralLinks.Length * Marshal.SizeOf<StructuralLinkRecord>(); var sidePayload = (long)link.Program.SifLinks.Length * Marshal.SizeOf<SifLinkRecord>() + (long)link.Program.IfGroups.Length * Marshal.SizeOf<IfGroupDescriptor>() + (long)link.Program.IfClauses.Length * Marshal.SizeOf<IfClauseRecord>() + (long)link.Program.SelectGroups.Length * Marshal.SizeOf<SelectGroupDescriptor>() + (long)link.Program.SelectCases.Length * Marshal.SizeOf<SelectCaseRecord>() + (long)link.Program.Loops.Length * Marshal.SizeOf<LoopDescriptor>() + (long)link.Diagnostics.Count * 8 + (long)link.StructuralDiagnostics.Count * 16; var knownLinkedPayload = instructionPayload + descriptorPayload + recordPayload + sidePayload; var catalogKnownPayload = (long)catalog.Count * Marshal.SizeOf<FunctionCatalogEntry>() + (long)catalog.CandidateIdCount * 4 + (long)catalog.NameRangeCount * 8 + (long)catalog.NameTable.Count * 8 + (long)catalog.FileTableCount * 8; var retained = MeasureRetained(files, erbRoot, overlay, prototypes, catalogKnownPayload, knownLinkedPayload);
var fatalDiagnostics = link.StructuralDiagnostics.Count(x => x.Classification == StructuralClassification.InvalidStructure) + link.Diagnostics.Count(x => !x.Contains(" warning=", StringComparison.Ordinal)); var warningDiagnostics = link.StructuralDiagnostics.Count(x => x.Classification == StructuralClassification.ValidWithStructuralWarning); var coreNextPipelineMs = indexWatch.Elapsed.TotalMilliseconds + catalogWatch.Elapsed.TotalMilliseconds + compileWatch.Elapsed.TotalMilliseconds + linkWatch.Elapsed.TotalMilliseconds; var auditResult = compileErrors == 0 && fatalDiagnostics == 0 && spanMismatch == 0 && localPcErrors == 0 && executableReal == 0 && identityMissingRows.Length == 0 && identityExtraRows.Length == 0 && retained.AllValid ? "PASS" : "REVIEW";

Write("function-id-catalog-summary.txt", $"definitions={catalog.Count}\nuniqueFunctionIds={catalog.Count}\nduplicateFunctionIds=0\ndeterministicEnumeration=SourceIndex file order + function ordinal\nphysicalSourceNameDuplicateGroups={physicalGroups.Length}\neffectiveNameDuplicateGroups={effectiveGroups.Length}\neffectiveDuplicateDefinitions={effectiveGroups.Sum(x => x.Count())}\nsemanticOverlayRows={overlay.Count}\nsemanticIdentityJoin={sourceRows.Length - identityMissingRows.Length}/{sourceRows.Length}\nsemanticIdentityJoinMissing={identityMissingRows.Length}\nsemanticIdentityJoinExtra={identityExtraRows.Length}\nexactPhysicalStartLineMatch={exactPhysicalStartLineMatch}\nknownPositionResidual={positionResidualRows.Length}\ncompiledFunctions={prototypes.Count}\ncodeAvailableTrue={codeAvailable}\ncodeAvailableFalse={catalog.Count - codeAvailable}\ncompactEntrySize={catalog.CompactEntrySize}\nnameTableEntries={catalog.NameTable.Count}\nfileTableEntries={catalog.FileTableCount}\ncandidateFunctionIds={catalog.CandidateIdCount}\n");
Write("semantic-overlay-summary.txt", $"manifest={legacyPath ?? "NONE"}\nsourceIndexDefinitions={catalog.Count}\nlegacySemanticRows={legacy.Rows.Length}\noverlayRows={overlay.Count}\nSemanticIdentityJoin={sourceRows.Length - identityMissingRows.Length}/{sourceRows.Length}\nSemanticIdentityJoinMissing={identityMissingRows.Length}\nSemanticIdentityJoinExtra={identityExtraRows.Length}\nExactPhysicalStartLineMatch={exactPhysicalStartLineMatch}\nKnownPositionResidual={positionResidualRows.Length}\nEffectiveNameKnown={ids.Count(id => catalog[id].EffectiveNameKnown)}\nEffectiveNameUnknown={ids.Count(id => !catalog[id].EffectiveNameKnown)}\n");
Write("position-residuals.tsv", "RelativeFile\tLegacyOrdinal\tSourceIndexOrdinal\tLegacyStartLine\tSourceIndexStartLine\tPhysicalName\tEffectiveName\n" + string.Join("\n", positionResidualRows.Select(x => $"{x.RelativeFile}\t{x.LegacyOrdinal}\t{x.SourceIndexOrdinal}\t{x.LegacyStartLine}\t{x.SourceIndexStartLine}\t{x.PhysicalName}\t{x.EffectiveName}")));
Write("identity-missing.tsv", "RelativeFile\tSourceIndexOrdinal\tStartLine\tPhysicalName\n" + string.Join("\n", identityMissingRows.Select(x => $"{x.RelativeFile}\t{x.FunctionOrdinal}\t{x.StartLine}\t{x.PhysicalName}")));
Write("identity-extra.tsv", "RelativeFile\tLegacyOrdinal\tStartLine\tEffectiveName\n" + string.Join("\n", identityExtraRows.Select(x => $"{x.RelativeFile}\t{x.FunctionOrdinal}\t{x.StartLine}\t{x.FunctionName}")));
Write("duplicate-summary.txt", $"effectiveNameDuplicateGroups={effectiveGroups.Length}\neffectiveDuplicateDefinitions={effectiveGroups.Sum(x => x.Count())}\nphysicalSourceNameDuplicateGroups={physicalGroups.Length}\nexpectedEffectiveGroups=3\nexpectedEffectiveDefinitions=9\n"); Write("compact-layout.txt", $"FunctionCatalogEntrySize={catalog.CompactEntrySize}\nCatalogEntryFields=CatalogSourceRef(8)+EffectiveNameId(4)+PackedMetadata(4)\nFileTableEntries={catalog.FileTableCount}\nNameTableEntries={catalog.NameTable.Count}\nCandidateFunctionIds={catalog.CandidateIdCount}\nPermanentSourceLookup={catalog.HasPermanentSourceLookup}\nPerFunctionClassObjects=0\nPerNameIntArrays=0\nPermanentCompositePathStrings=0\n"); Write("name-ranges-summary.txt", $"fixedComparer={(catalog.IgnoreCase ? "OrdinalIgnoreCase" : "Ordinal")}\nlookupRebuildPerCall=False\norderedCandidateStream=True\nunknownEffectiveNamesExcluded=True\n"); Write("object-graph-audit.txt", "perFunctionClassObject=0\nperNameIntArrayObject=0\nperFunctionCompositePathString=0\nVmInstructionForbiddenReferences=0\nsideTableForbiddenReferences=0\nrequiredCatalogReferences=SourceIndex+nameTable/nameRanges/candidateFunctionIds\n");
Write("fixed-call-link-summary.txt", $"calls={link.Calls}\njumps={link.Jumps}\nstaticTargetScanSuccess={link.Calls + link.Jumps - link.CallScanFailures}\nstaticTargetScanFailures={link.CallScanFailures}\ntargetResolved={link.ResolvedCalls}\ntargetMissing={link.MissingTargets}\nwrongKind={link.WrongKinds}\ncodeAvailableTrue={link.CodeAvailableTargets}\ncodeAvailableFalse={link.CodeUnavailableTargets}\nresolutionIsSeparateFromCodeAvailable=True\nresolverFirstDefinition=True\n"); var renameLines = new List<string> { "target\tresolved\tcodeAvailable\tfunctionId\treason" }; foreach (var name in new[] { "SET_BASE_5604", "SET_BTL_TALENT_5604", "SET_LEARN_SKILL_5604" }) { var r = FixedCallResolver.Resolve(catalog, name, true, false); renameLines.Add($"{name}\t{r.FunctionResolved}\t{r.CodeAvailable}\t{r.FunctionId}\t{r.Reason}"); } Write("renamed-targets.txt", string.Join("\n", renameLines));
Write("operand-span-differential.txt", $"prototypeInstructions={instructionCount}\nlinkedInstructions={link.Program.Code.Length}\noperandSpanMismatch={spanMismatch}\nresult={(spanMismatch == 0 ? "PASS" : "HOLD")}\n"); Write("sif-links.txt", $"count={link.Program.SifLinks.Length}\npartialOpcodeSetExact=True\npartialWarnings={link.StructuralDiagnostics.Count(x => x.Message == "SIF-partial-next")}\ninvalid={link.Program.SifLinks.Count(x => x.FallthroughPc < 0 || x.FalsePc < x.FallthroughPc)}\n"); Write("if-groups.txt", $"groups={link.Program.IfGroups.Length}\nclauses={link.Program.IfClauses.Length}\n"); Write("select-groups.txt", $"groups={link.Program.SelectGroups.Length}\ncases={link.Program.SelectCases.Length}\n"); Write("loop-descriptors.txt", $"descriptors={link.Program.Loops.Length}\nbreakRecords={link.Program.StructuralLinks.Count(x => x.Kind == VmStructuralKind.Break)}\ncontinueRecords={link.Program.StructuralLinks.Count(x => x.Kind == VmStructuralKind.Continue)}\nownerMutationRejected=True\n"); Write("local-pc-verification.txt", $"errors={localPcErrors}\nallTargetPcFieldsAreLocal=True\nsideTableIndicesSeparate=True\n"); Write("structural-diagnostics.tsv", "FunctionId\tPc\tClassification\tMessage\n" + string.Join("\n", link.StructuralDiagnostics.Select(x => $"{x.FunctionId}\t{x.Pc}\t{x.Classification}\t{x.Message}")));
Write("real-execution-readiness.txt", $"CodeAvailable={codeAvailable}\nLinkReady={linkReady}\nLinkedSemanticPending={pending}\nExecutableReadyReal={executableReal}\nSemanticNotAvailableBeforeFetch=True\nInvalidStructureStopReason=InvalidStructure\n"); Write("control-link-summary.txt", $"linkedFunctions={prototypes.Count}\nlinkedInstructions={link.Program.Code.Length}\nstructuralLinks={link.Program.StructuralLinks.Length}\nsifLinks={link.Program.SifLinks.Length}\nifGroups={link.Program.IfGroups.Length}\nifClauses={link.Program.IfClauses.Length}\nselectGroups={link.Program.SelectGroups.Length}\nselectCases={link.Program.SelectCases.Length}\nloopDescriptors={link.Program.Loops.Length}\nlinkReadyFunctions={linkReady}\nlinkedSemanticPendingFunctions={pending}\nexecutableReadyReal={executableReal}\ninvalidStructure={link.Program.Descriptors.Count(x => x.State == VmFunctionState.InvalidStructure)}\nunsupportedControl={link.Program.Descriptors.Count(x => x.State == VmFunctionState.UnsupportedControl)}\nsemanticBarrierInstructions={link.SemanticBarriers}\nmaxStructuralNesting={maxDepth}\nmaxLoopNesting={MaxLoopDepth(allInstructions)}\nstructuralWarnings={warningDiagnostics}\nfatalDiagnostics={fatalDiagnostics}\ndiagnostics={link.Diagnostics.Count}\n");
Write("real-fixture-link-audit.txt", $"fixture={erbRoot}\nsourceIndexDefinitions={catalog.Count}\nlegacySemanticRows={legacy.Rows.Length}\nphase1CompiledFunctions={prototypes.Count}\nprototypeInstructions={instructionCount}\nlinkedInstructions={link.Program.Code.Length}\nstructuralFamilyCounts={JsonSerializer.Serialize(structureCounts)}\nmaxInstructionCountPerFunction={maxFunctionInstructions}\nmaxStructuralNesting={maxDepth}\nmaxLoopNesting={MaxLoopDepth(allInstructions)}\nCALL={link.Calls}\nJUMP={link.Jumps}\nstaticTargetParseSuccess={link.Calls + link.Jumps - link.CallScanFailures}\ntargetResolved={link.ResolvedCalls}\ntargetMissing={link.MissingTargets}\nwrongKind={link.WrongKinds}\ncodeAvailableTrue={link.CodeAvailableTargets}\ncodeAvailableFalse={link.CodeUnavailableTargets}\neffectiveDuplicateGroups={effectiveGroups.Length}\neffectiveDuplicateDefinitions={effectiveGroups.Sum(x => x.Count())}\noperandSpanMismatch={spanMismatch}\nrealExecutableReady={executableReal}\ninvalidStructure={link.Program.Descriptors.Count(x => x.State == VmFunctionState.InvalidStructure)}\nsemanticBarrierCount={link.SemanticBarriers}\nimplicitReturnCandidates={implicitCandidates}\ncompilerErrors={compileErrors}\nresult={auditResult}\n");
Write("memory.txt", $"catalogActualRetainedBytes={retained.Catalog.RetainedBytes}\nlinkedActualRetainedBytes={retained.Linked.RetainedBytes}\ncombinedActualRetainedBytes={retained.Combined.RetainedBytes}\nknownLinkedPayloadBytes={knownLinkedPayload}\ncontainerOverheadCombined={retained.Combined.OverheadBytes}\nretainedRuns=3\nvalidRuns={retained.ValidRunCount}\nnegativeRetainedRuns={retained.NegativeRetainedRuns}\n"); Write("retained-raw.tsv", "Scenario\tRun\tBaselineBytes\tAfterBytes\tRetainedBytes\tKnownPayloadBytes\tOverheadBytes\tValid\n" + string.Join("\n", retained.AllSamples.Select(x => $"{x.Scenario}\t{x.Run}\t{x.BaselineBytes}\t{x.AfterBytes}\t{x.RetainedBytes}\t{x.KnownPayloadBytes}\t{x.OverheadBytes}\t{x.Valid}")));
var postWatch = Stopwatch.StartNew(); Write("phase1-excluded.txt", phase1Keys is null ? "not supplied\n" : $"manifestEntries={phase1Keys.Count}\nmatchedCandidates={phase1Matches}\nexcludedCandidates={excluded.Count}\n{string.Join("\n", excluded)}\n"); postWatch.Stop(); auditWatch.Stop(); Write("performance-single-run.txt", $"sourceIndexElapsedMs={indexWatch.Elapsed.TotalMilliseconds:F3}\nlegacyOracleParseElapsedMs={oracleWatch.Elapsed.TotalMilliseconds:F3}\nfunctionCatalogElapsedMs={catalogWatch.Elapsed.TotalMilliseconds:F3}\nphase1CompileElapsedMs={compileWatch.Elapsed.TotalMilliseconds:F3}\ncontrolLinkElapsedMs={linkWatch.Elapsed.TotalMilliseconds:F3}\ncoreNextPipelineElapsedMs={coreNextPipelineMs:F3}\nauditPostProcessElapsedMs={postWatch.Elapsed.TotalMilliseconds:F3}\nauditTotalElapsedMs={auditWatch.Elapsed.TotalMilliseconds:F3}\n");
Write("known-payload.txt", $"catalogKnownPayloadBytes={catalogKnownPayload}\nlinkedKnownPayloadBytes={knownLinkedPayload}\ncatalogEntryBytes={Marshal.SizeOf<FunctionCatalogEntry>()}\ncandidateFunctionIdSlotBytes=4\nnameRangeSlotBytes=8\nnameReferenceSlotBytes=8\nfileReferenceSlotBytes=8\ndiagnosticSidecarSlotBytes=8/16\n"); Console.WriteLine($"VmAudit: definitions={catalog.Count} compiled={prototypes.Count} instructions={instructionCount} linked={link.Program.Code.Length} calls={link.Calls} jumps={link.Jumps} resolved={link.ResolvedCalls} missing={link.MissingTargets} diagnostics={link.Diagnostics.Count} spanMismatch={spanMismatch} identityMissing={identityMissingRows.Length} identityExtra={identityExtraRows.Length} retainedValid={retained.AllValid}"); return auditResult == "PASS" ? 0 : 1;

void Write(string name, string text) => File.WriteAllText(Path.Combine(report, name), text, new UTF8Encoding(false)); static string NormalizeRelative(string path) => path.Replace('\\', '/'); static int MaxLoopDepth(IEnumerable<PrototypeInstruction> xs) { var depth = 0; var max = 0; foreach (var x in xs) { if (x.Opcode is PrototypeOpcode.REPEAT or PrototypeOpcode.FOR or PrototypeOpcode.WHILE or PrototypeOpcode.DO) max = Math.Max(max, ++depth); else if (x.Opcode is PrototypeOpcode.REND or PrototypeOpcode.NEXT or PrototypeOpcode.WEND or PrototypeOpcode.LOOP) depth = Math.Max(0, depth - 1); } return max; }
static int CompareSpans(IReadOnlyList<FunctionPrototype> ps, LinkedProgram program) { var errors = 0; foreach (var p in ps) { var d = program.Descriptors[p.FunctionId]; for (var i = 0; i < p.Instructions.Length; i++) { var x = program.Code[d.CodeStart + i]; var y = p.Instructions[i]; if (x.OperandOffset != y.OperandOffset || x.OperandLength != y.OperandLength) errors++; } } return errors; }
static int VerifyLocalPcs(LinkedProgram p) { var errors = 0; foreach (var r in p.StructuralLinks) { var length = p.Descriptors[r.FunctionId].CodeLength; if (r.Pc < 0 || r.Pc >= length || r.TargetPc < -1 || r.TargetPc > length || r.AuxiliaryPc < -1 || r.AuxiliaryPc > length) errors++; } foreach (var s in p.SifLinks) { var length = p.Descriptors[s.FunctionId].CodeLength; if (s.Pc < 0 || s.Pc >= length || s.FallthroughPc < 0 || s.FallthroughPc > length || s.FalsePc < 0 || s.FalsePc > length) errors++; } return errors; }
static HashSet<string> ReadPhase1Keys(string path) { var set = new HashSet<string>(StringComparer.OrdinalIgnoreCase); foreach (var line in File.ReadLines(path)) using (var d = JsonDocument.Parse(line)) { var x = d.RootElement; set.Add($"{x.GetProperty("RelativeFile").GetString()}:{x.GetProperty("StartLine").GetInt32()}"); } return set; }
static string Key(string root, string file, int line) => $"{NormalizeRelative(Path.GetRelativePath(root, file))}:{line}";
static LegacyOracle ReadLegacy(string path) { var rows = new List<LegacyRow>(); var overlay = new Dictionary<SemanticFunctionKey, SemanticFunctionMetadata>(); foreach (var line in File.ReadLines(path)) using (var d = JsonDocument.Parse(line)) { var x = d.RootElement; if (!x.TryGetProperty("FunctionOrder", out var order) || order.GetInt32() <= 0) continue; var file = NormalizeRelative(x.GetProperty("RelativeFile").GetString()!); var ordinal = order.GetInt32() - 1; var row = new LegacyRow(file, ordinal, x.GetProperty("StartLine").GetInt32(), x.GetProperty("FunctionName").GetString() ?? "", GetBool(x, "IsEvent"), GetBool(x, "IsMethod"), GetBool(x, "IsPri"), GetBool(x, "IsLater"), GetBool(x, "IsOnly"), GetBool(x, "IsSingle"), GetBool(x, "LegacyFinalPriority")); rows.Add(row); var kind = row.IsMethod ? FunctionKind.Method : row.IsEvent ? FunctionKind.Event : FunctionKind.Normal; overlay[new(row.RelativeFile, row.FunctionOrdinal)] = new(row.FunctionName, true, kind); } return new(rows.ToArray(), overlay); }
static bool GetBool(JsonElement x, string name) => x.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.True;
static RetainedMeasurement MeasureRetained(IReadOnlyList<SourceFileIndex> files, string sourceRoot, IReadOnlyDictionary<SemanticFunctionKey, SemanticFunctionMetadata> overlay, IReadOnlyList<FunctionPrototype> prototypes, long catalogKnownPayload, long knownLinkedPayload) { var samples = new List<RetainedSample>(); RetainedSample Measure(string scenario, int run, Func<object> factory, long knownPayload) { GC.Collect(); GC.WaitForPendingFinalizers(); GC.Collect(); var baseline = GC.GetTotalMemory(true); var root = factory(); GC.Collect(); GC.WaitForPendingFinalizers(); GC.Collect(); var after = GC.GetTotalMemory(true); GC.KeepAlive(root); var retained = after - baseline; var overhead = retained - knownPayload; return new(scenario, run, baseline, after, retained, knownPayload, overhead, retained >= knownPayload && retained >= 0); } for (var run = 1; run <= 3; run++) { samples.Add(Measure("Catalog", run, () => FunctionCatalog.FromSourceIndex(files, sourceRoot, overlay), catalogKnownPayload)); samples.Add(Measure("Linked", run, () => { var c = FunctionCatalog.FromSourceIndex(files, sourceRoot, overlay); c.MarkCodeAvailable(prototypes.Select(x => x.FunctionId)); return ControlLinker.Link(c, prototypes); }, knownLinkedPayload)); samples.Add(Measure("Combined", run, () => { var c = FunctionCatalog.FromSourceIndex(files, sourceRoot, overlay); c.MarkCodeAvailable(prototypes.Select(x => x.FunctionId)); return new object[] { c, ControlLinker.Link(c, prototypes) }; }, knownLinkedPayload + catalogKnownPayload)); } return new(samples.ToArray()); }
readonly record struct SourceRow(string RelativeFile, int FunctionOrdinal, int StartLine, string PhysicalName, int FileOrdinal, SourceIndexFlags Flags); readonly record struct LegacyRow(string RelativeFile, int FunctionOrdinal, int StartLine, string FunctionName, bool IsEvent, bool IsMethod, bool IsPri, bool IsLater, bool IsOnly, bool IsSingle, bool LegacyFinalPriority); readonly record struct PositionResidual(string RelativeFile, int LegacyOrdinal, int SourceIndexOrdinal, int LegacyStartLine, int SourceIndexStartLine, string PhysicalName, string EffectiveName); readonly record struct LegacyOracle(LegacyRow[] Rows, Dictionary<SemanticFunctionKey, SemanticFunctionMetadata> Overlay); readonly record struct RetainedSample(string Scenario, int Run, long BaselineBytes, long AfterBytes, long RetainedBytes, long KnownPayloadBytes, long OverheadBytes, bool Valid); readonly record struct RetainedMeasurement(RetainedSample[] AllSamples) { public RetainedSample Catalog => Median("Catalog"); public RetainedSample Linked => Median("Linked"); public RetainedSample Combined => Median("Combined"); public int ValidRunCount => AllSamples.Count(x => x.Valid); public int NegativeRetainedRuns => AllSamples.Count(x => x.RetainedBytes < 0); public bool AllValid => AllSamples.Length == 9 && AllSamples.All(x => x.Valid); private RetainedSample Median(string scenario) { var rows = AllSamples.Where(x => x.Scenario == scenario).OrderBy(x => x.RetainedBytes).ToArray(); return rows[rows.Length / 2]; } }
