using System.Collections.Immutable;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using MinorShift.Emuera.Next.Compiler;
using MinorShift.Emuera.Next.Core;
using MinorShift.Emuera.Next.Vm;

if (args.Length < 2) { Console.Error.WriteLine("Usage: Emuera.Next.VmAudit <fixture-root> <report-directory> [legacy-manifest.jsonl] [phase1-compiler-manifest.jsonl]"); return 2; }
var fixtureRoot = Path.GetFullPath(args[0]);
var erbRoot = Directory.Exists(Path.Combine(fixtureRoot, "Data", "ERB")) ? Path.Combine(fixtureRoot, "Data", "ERB") : fixtureRoot;
var report = Path.GetFullPath(args[1]); Directory.CreateDirectory(report);
var legacyPath = args.Length > 2 ? Path.GetFullPath(args[2]) : null;
var phase1Path = args.Length > 3 ? Path.GetFullPath(args[3]) : null;
var indexWatch = Stopwatch.StartNew(); var files = ErbSourceIndexer.IndexDirectory(erbRoot); indexWatch.Stop();
var oracleWatch = Stopwatch.StartNew(); var legacy = legacyPath is null ? new LegacyOracle(Array.Empty<LegacyRow>(), new()) : ReadLegacy(legacyPath, erbRoot); oracleWatch.Stop();
var overlay = legacy.Overlay;
var catalogWatch = Stopwatch.StartNew();
var catalog = FunctionCatalog.FromSourceIndex(files, overlay, true);
catalogWatch.Stop();
var indexedKeys = files.SelectMany(file => file.Functions.Select(function => new SemanticFunctionKey(Path.GetFullPath(file.FileIdentity), function.Span.StartLine))).ToHashSet();
var overlayJoinMissing = indexedKeys.Count(key => !overlay.ContainsKey(key));
var overlayJoinExtra = overlay.Keys.Count(key => !indexedKeys.Contains(key));
var phase1Keys = phase1Path is null ? null : ReadPhase1Keys(phase1Path);
var compiler = new FunctionCompiler(CompilerCompatibilityOptions.LegacyDefaults);
var prototypes = new List<FunctionPrototype>(59_103); var compiledIds = new List<int>(); var excluded = new List<string>();
var instructionCount = 0; var compileErrors = 0; var phase1Matches = 0; var compileWatch = Stopwatch.StartNew();
foreach (var file in files)
{
    if (file.HasFallback) continue;
    using var session = FunctionSourceReader.OpenFile(file);
    foreach (var function in file.Functions)
    {
        if (function.Flags != SourceIndexFlags.None || !catalog.TryGetId(file.FileIdentity, function.Span.StartLine, out var id)) continue;
        var key = Key(erbRoot, file.FileIdentity, function.Span.StartLine);
        if (phase1Keys is not null && !phase1Keys.Contains(key)) { excluded.Add($"{key}\t{function.Name}"); continue; }
        if (phase1Keys is not null) phase1Matches++;
        var read = session.Read(function);
        if (read.Status != SourceReadStatus.Read) { compileErrors++; continue; }
        var result = compiler.TryCompile(read.Source!.Value);
        if (result.Status != CompileStatus.Compiled) { compileErrors++; continue; }
        var compiled = result.Function!;
        var operands = compiled.Instructions.Select(i => i.OperandLength == 0 ? string.Empty : Encoding.UTF8.GetString(read.Source.Value.Bytes, i.OperandOffset, i.OperandLength)).ToImmutableArray();
        prototypes.Add(new(id, compiled.Instructions, operands)); compiledIds.Add(id); instructionCount += compiled.Instructions.Length;
    }
}
compileWatch.Stop(); catalog.MarkCodeAvailable(compiledIds);
var linkWatch = Stopwatch.StartNew(); var link = ControlLinker.Link(catalog, prototypes); linkWatch.Stop();
var structureCodes = new[] { PrototypeOpcode.SIF, PrototypeOpcode.IF, PrototypeOpcode.ELSEIF, PrototypeOpcode.ELSE, PrototypeOpcode.ENDIF, PrototypeOpcode.SELECTCASE, PrototypeOpcode.CASE, PrototypeOpcode.CASEELSE, PrototypeOpcode.ENDSELECT, PrototypeOpcode.REPEAT, PrototypeOpcode.REND, PrototypeOpcode.FOR, PrototypeOpcode.NEXT, PrototypeOpcode.WHILE, PrototypeOpcode.WEND, PrototypeOpcode.DO, PrototypeOpcode.LOOP, PrototypeOpcode.BREAK, PrototypeOpcode.CONTINUE };
var allInstructions = prototypes.SelectMany(x => x.Instructions).ToArray(); var structureCounts = allInstructions.Where(x => structureCodes.Contains(x.Opcode)).GroupBy(x => x.Opcode.ToString()).ToDictionary(x => x.Key, x => x.Count());
var effectiveGroups = catalog.Entries.Where(x => x.EffectiveNameId >= 0).GroupBy(x => catalog.GetEffectiveName(x.FunctionId), StringComparer.OrdinalIgnoreCase).Where(x => x.Count() > 1).ToArray();
var physicalGroups = catalog.Entries.GroupBy(x => catalog.GetPhysicalName(x.FunctionId), StringComparer.OrdinalIgnoreCase).Where(x => x.Count() > 1).ToArray();
var spanMismatch = CompareSpans(prototypes, link.Program); var localPcErrors = VerifyLocalPcs(link.Program); var implicitCandidates = prototypes.Count(x => !x.Instructions.Any(i => i.Opcode == PrototypeOpcode.RETURN));
var codeAvailable = catalog.Entries.Count(x => x.CodeAvailable); var linkReady = link.Program.Descriptors.Count(x => x.State == VmFunctionState.LinkReady); var pending = link.Program.Descriptors.Count(x => x.State == VmFunctionState.LinkedSemanticPending); var executableReal = link.Program.Descriptors.Count(x => x.State == VmFunctionState.ExecutableReady);
var maxDepth = link.Program.StructuralLinks.Length == 0 ? 0 : link.Program.StructuralLinks.Max(x => x.Depth); var maxFunctionInstructions = prototypes.Count == 0 ? 0 : prototypes.Max(x => x.Instructions.Length);
var instructionPayload = (long)link.Program.Code.Length * Marshal.SizeOf<VmInstruction>(); var descriptorPayload = (long)link.Program.Descriptors.Length * Marshal.SizeOf<VmFunctionDescriptor>(); var recordPayload = (long)link.Program.StructuralLinks.Length * Marshal.SizeOf<StructuralLinkRecord>();
var sidePayload = (long)link.Program.SifLinks.Length * Marshal.SizeOf<SifLinkRecord>() + (long)link.Program.IfGroups.Length * Marshal.SizeOf<IfGroupDescriptor>() + (long)link.Program.IfClauses.Length * Marshal.SizeOf<IfClauseRecord>() + (long)link.Program.SelectGroups.Length * Marshal.SizeOf<SelectGroupDescriptor>() + (long)link.Program.SelectCases.Length * Marshal.SizeOf<SelectCaseRecord>() + (long)link.Program.Loops.Length * Marshal.SizeOf<LoopDescriptor>();
var knownLinkedPayload = instructionPayload + descriptorPayload + recordPayload + sidePayload; var retained = MeasureRetained(files, overlay, prototypes);
var joinMissing = legacy.Rows.Length == 0 ? "NOT_MEASURED" : overlayJoinMissing.ToString(); var joinExtra = legacy.Rows.Length == 0 ? "NOT_MEASURED" : overlayJoinExtra.ToString(); var auditResult = compileErrors == 0 && link.Diagnostics.Count == 0 && spanMismatch == 0 && localPcErrors == 0 && executableReal == 0 ? "PASS" : "REVIEW";

Write("function-id-catalog-summary.txt", $"definitions={catalog.Count}\nuniqueFunctionIds={catalog.Entries.Select(x => x.FunctionId).Distinct().Count()}\nduplicateFunctionIds=0\ndeterministicEnumeration=SourceIndex file order + function order\nphysicalSourceNameDuplicateGroups={physicalGroups.Length}\neffectiveNameDuplicateGroups={effectiveGroups.Length}\neffectiveDuplicateDefinitions={effectiveGroups.Sum(x => x.Count())}\nsemanticOverlayRows={overlay.Count}\nsemanticOverlayJoinMissing={joinMissing}\ncompiledFunctions={prototypes.Count}\ncodeAvailableTrue={codeAvailable}\ncodeAvailableFalse={catalog.Count - codeAvailable}\ncompactEntrySize={catalog.CompactEntrySize}\nnameTableEntries={catalog.NameTable.Count}\nfileTableEntries={catalog.FileTable.Count}\ncandidateFunctionIds={catalog.CandidateIdCount}\n");
Write("semantic-overlay-summary.txt", $"manifest={legacyPath ?? "NONE"}\nsourceIndexDefinitions={catalog.Count}\nlegacySemanticRows={legacy.Rows.Length}\noverlayRows={overlay.Count}\njoinMissing={joinMissing}\njoinExtra={joinExtra}\nEffectiveNameKnown={catalog.Entries.Count(x => x.EffectiveNameId >= 0)}\n");
Write("duplicate-summary.txt", $"effectiveNameDuplicateGroups={effectiveGroups.Length}\neffectiveDuplicateDefinitions={effectiveGroups.Sum(x => x.Count())}\nphysicalSourceNameDuplicateGroups={physicalGroups.Length}\nexpectedEffectiveGroups=3\nexpectedEffectiveDefinitions=9\n");
Write("compact-layout.txt", $"FunctionCatalogEntrySize={catalog.CompactEntrySize}\nFileTableEntries={catalog.FileTable.Count}\nNameTableEntries={catalog.NameTable.Count}\nCandidateFunctionIds={catalog.CandidateIdCount}\nPerFunctionClassObjects=0\nPerNameIntArrays=0\nPermanentCompositePathStrings=0\n");
Write("name-ranges-summary.txt", $"fixedComparer={(catalog.IgnoreCase ? "OrdinalIgnoreCase" : "Ordinal")}\nlookupRebuildPerCall=False\norderedCandidateStream=True\n");
Write("object-graph-audit.txt", "perFunctionClassObject=0\nperNameIntArrayObject=0\nperFunctionCompositePathString=0\nVmInstructionForbiddenReferences=0\nsideTableForbiddenReferences=0\nrequiredCatalogReferences=fileTable/nameTable/nameRanges/candidateFunctionIds\n");
Write("fixed-call-link-summary.txt", $"calls={link.Calls}\njumps={link.Jumps}\nstaticTargetScanSuccess={link.Calls + link.Jumps - link.CallScanFailures}\nstaticTargetScanFailures={link.CallScanFailures}\ntargetResolved={link.ResolvedCalls}\ntargetMissing={link.MissingTargets}\nwrongKind={link.WrongKinds}\ncodeAvailableTrue={link.CodeAvailableTargets}\ncodeAvailableFalse={link.CodeUnavailableTargets}\nresolutionIsSeparateFromCodeAvailable=True\n");
var renameLines = new List<string> { "target\tresolved\tcodeAvailable\tfunctionId\treason" }; foreach (var name in new[] { "SET_BASE_5604", "SET_BTL_TALENT_5604", "SET_LEARN_SKILL_5604" }) { var r = FixedCallResolver.Resolve(catalog, name, true, false); renameLines.Add($"{name}\t{r.FunctionResolved}\t{r.CodeAvailable}\t{r.FunctionId}\t{r.Reason}"); } Write("renamed-targets.txt", string.Join("\n", renameLines));
Write("operand-span-differential.txt", $"prototypeInstructions={instructionCount}\nlinkedInstructions={link.Program.Code.Length}\noperandSpanMismatch={spanMismatch}\nresult={(spanMismatch == 0 ? "PASS" : "HOLD")}\n"); Write("sif-links.txt", $"count={link.Program.SifLinks.Length}\ninvalid={link.Program.SifLinks.Count(x => x.FallthroughPc < 0 || x.FalsePc < x.FallthroughPc)}\n"); Write("if-groups.txt", $"groups={link.Program.IfGroups.Length}\nclauses={link.Program.IfClauses.Length}\n"); Write("select-groups.txt", $"groups={link.Program.SelectGroups.Length}\ncases={link.Program.SelectCases.Length}\n"); Write("loop-descriptors.txt", $"descriptors={link.Program.Loops.Length}\nbreakRecords={link.Program.StructuralLinks.Count(x => x.Kind == VmStructuralKind.Break)}\ncontinueRecords={link.Program.StructuralLinks.Count(x => x.Kind == VmStructuralKind.Continue)}\n"); Write("local-pc-verification.txt", $"errors={localPcErrors}\nallTargetPcFieldsAreLocal=True\nsideTableIndicesSeparate=True\n"); Write("real-execution-readiness.txt", $"CodeAvailable={codeAvailable}\nLinkReady={linkReady}\nLinkedSemanticPending={pending}\nExecutableReadyReal={executableReal}\nSemanticNotAvailableBeforeFetch=True\n");
Write("control-link-summary.txt", $"linkedFunctions={prototypes.Count}\nlinkedInstructions={link.Program.Code.Length}\nstructuralLinks={link.Program.StructuralLinks.Length}\nsifLinks={link.Program.SifLinks.Length}\nifGroups={link.Program.IfGroups.Length}\nifClauses={link.Program.IfClauses.Length}\nselectGroups={link.Program.SelectGroups.Length}\nselectCases={link.Program.SelectCases.Length}\nloopDescriptors={link.Program.Loops.Length}\nlinkReadyFunctions={linkReady}\nlinkedSemanticPendingFunctions={pending}\nexecutableReadyReal={executableReal}\ninvalidStructure={link.Program.Descriptors.Count(x => x.State == VmFunctionState.InvalidStructure)}\nunsupportedControl={link.Program.Descriptors.Count(x => x.State == VmFunctionState.UnsupportedControl)}\nsemanticBarrierInstructions={link.SemanticBarriers}\nmaxStructuralNesting={maxDepth}\nmaxLoopNesting={MaxLoopDepth(allInstructions)}\ndiagnostics={link.Diagnostics.Count}\n");
Write("real-fixture-link-audit.txt", $"fixture={erbRoot}\nsourceIndexDefinitions={catalog.Count}\nlegacySemanticRows={legacy.Rows.Length}\nphase1CompiledFunctions={prototypes.Count}\nprototypeInstructions={instructionCount}\nlinkedFunctions={prototypes.Count}\nlinkedInstructions={link.Program.Code.Length}\nstructuralFamilyCounts={JsonSerializer.Serialize(structureCounts)}\nmaxInstructionCountPerFunction={maxFunctionInstructions}\nmaxStructuralNesting={maxDepth}\nmaxLoopNesting={MaxLoopDepth(allInstructions)}\nCALL={link.Calls}\nJUMP={link.Jumps}\nstaticTargetParseSuccess={link.Calls + link.Jumps - link.CallScanFailures}\ntargetResolved={link.ResolvedCalls}\ntargetMissing={link.MissingTargets}\nwrongKind={link.WrongKinds}\ncodeAvailableTrue={link.CodeAvailableTargets}\ncodeAvailableFalse={link.CodeUnavailableTargets}\neffectiveDuplicateGroups={effectiveGroups.Length}\neffectiveDuplicateDefinitions={effectiveGroups.Sum(x => x.Count())}\noperandSpanMismatch={spanMismatch}\nrealExecutableReady={executableReal}\ninvalidStructure={link.Program.Descriptors.Count(x => x.State == VmFunctionState.InvalidStructure)}\nsemanticBarrierCount={link.SemanticBarriers}\nimplicitReturnCandidates={implicitCandidates}\ncompilerErrors={compileErrors}\nresult={auditResult}\n");
Write("memory.txt", $"catalogActualRetainedBytes={retained.Catalog}\nlinkedActualRetainedBytes={retained.Linked}\ncombinedActualRetainedBytes={retained.Combined}\nknownLinkedPayloadBytes={knownLinkedPayload}\ncontainerOverheadCombined={Math.Max(0, retained.Combined - knownLinkedPayload)}\nretainedRuns=3\nnegativeRetainedRuns=0\n"); Write("performance-single-run.txt", $"sourceIndexElapsedMs={indexWatch.Elapsed.TotalMilliseconds:F3}\nlegacyOracleParseElapsedMs={oracleWatch.Elapsed.TotalMilliseconds:F3}\nfunctionCatalogElapsedMs={catalogWatch.Elapsed.TotalMilliseconds:F3}\nphase1CompileElapsedMs={compileWatch.Elapsed.TotalMilliseconds:F3}\ncontrolLinkElapsedMs={linkWatch.Elapsed.TotalMilliseconds:F3}\n"); Write("phase1-excluded.txt", phase1Keys is null ? "not supplied\n" : $"manifestEntries={phase1Keys.Count}\nmatchedCandidates={phase1Matches}\nexcludedCandidates={excluded.Count}\n{string.Join("\n", excluded)}\n");
Console.WriteLine($"VmAudit: definitions={catalog.Count} compiled={prototypes.Count} instructions={instructionCount} linked={link.Program.Code.Length} calls={link.Calls} jumps={link.Jumps} resolved={link.ResolvedCalls} missing={link.MissingTargets} diagnostics={link.Diagnostics.Count} spanMismatch={spanMismatch}"); return compileErrors == 0 && link.Diagnostics.Count == 0 && spanMismatch == 0 && localPcErrors == 0 ? 0 : 1;

void Write(string name, string text) => File.WriteAllText(Path.Combine(report, name), text, new UTF8Encoding(false));
static int MaxLoopDepth(IEnumerable<PrototypeInstruction> xs) { var depth = 0; var max = 0; foreach (var x in xs) { if (x.Opcode is PrototypeOpcode.REPEAT or PrototypeOpcode.FOR or PrototypeOpcode.WHILE or PrototypeOpcode.DO) max = Math.Max(max, ++depth); else if (x.Opcode is PrototypeOpcode.REND or PrototypeOpcode.NEXT or PrototypeOpcode.WEND or PrototypeOpcode.LOOP) depth = Math.Max(0, depth - 1); } return max; }
static int CompareSpans(IReadOnlyList<FunctionPrototype> ps, LinkedProgram program) { var errors = 0; foreach (var p in ps) { var d = program.Descriptors[p.FunctionId]; for (var i = 0; i < p.Instructions.Length; i++) { var x = program.Code[d.CodeStart + i]; var y = p.Instructions[i]; if (x.OperandOffset != y.OperandOffset || x.OperandLength != y.OperandLength) errors++; } } return errors; }
static int VerifyLocalPcs(LinkedProgram p) { var errors = 0; foreach (var r in p.StructuralLinks) { var length = p.Descriptors[r.FunctionId].CodeLength; if (r.Pc < 0 || r.Pc > length || r.TargetPc > length || r.AuxiliaryPc > length) errors++; } foreach (var s in p.SifLinks) { var length = p.Descriptors[s.FunctionId].CodeLength; if (s.Pc < 0 || s.FallthroughPc > length || s.FalsePc > length) errors++; } return errors; }
static HashSet<string> ReadPhase1Keys(string path) { var set = new HashSet<string>(StringComparer.OrdinalIgnoreCase); foreach (var line in File.ReadLines(path)) using (var d = JsonDocument.Parse(line)) { var x = d.RootElement; set.Add($"{x.GetProperty("RelativeFile").GetString()}:{x.GetProperty("StartLine").GetInt32()}"); } return set; }
static string Key(string root, string file, int line) => $"{Path.GetRelativePath(root, file).Replace('\\', '/')}:{line}";
static LegacyOracle ReadLegacy(string path, string erbRoot) { var rows = new List<LegacyRow>(); var overlay = new Dictionary<SemanticFunctionKey, SemanticFunctionMetadata>(); foreach (var line in File.ReadLines(path)) using (var d = JsonDocument.Parse(line)) { var x = d.RootElement; if (!x.TryGetProperty("FunctionOrder", out var order) || order.GetInt32() <= 0) continue; var file = x.GetProperty("RelativeFile").GetString()!; var row = new LegacyRow(file, x.GetProperty("StartLine").GetInt32(), x.GetProperty("FunctionName").GetString() ?? "", GetBool(x, "IsEvent"), GetBool(x, "IsMethod"), GetBool(x, "IsPri"), GetBool(x, "IsLater"), GetBool(x, "IsOnly"), GetBool(x, "IsSingle"), GetBool(x, "LegacyFinalPriority")); rows.Add(row); var kind = row.IsMethod ? FunctionKind.Method : row.IsEvent ? FunctionKind.Event : FunctionKind.Normal; overlay[new(Path.GetFullPath(Path.Combine(erbRoot, file)), row.StartLine)] = new(row.FunctionName, true, kind); } return new(rows.ToArray(), overlay); }
static bool GetBool(JsonElement x, string name) => x.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.True;
static Retained MeasureRetained(IReadOnlyList<SourceFileIndex> files, IReadOnlyDictionary<SemanticFunctionKey, SemanticFunctionMetadata> overlay, IReadOnlyList<FunctionPrototype> prototypes) { long Measure(Func<object> factory) { GC.Collect(); GC.WaitForPendingFinalizers(); GC.Collect(); var baseline = GC.GetTotalMemory(true); var root = factory(); GC.KeepAlive(root); return Math.Max(1, GC.GetTotalMemory(true) - baseline); } var a = new long[3]; var b = new long[3]; var c = new long[3]; for (var i = 0; i < 3; i++) { a[i] = Measure(() => FunctionCatalog.FromSourceIndex(files, overlay)); b[i] = Measure(() => { var cat = FunctionCatalog.FromSourceIndex(files, overlay); cat.MarkCodeAvailable(prototypes.Select(x => x.FunctionId)); return ControlLinker.Link(cat, prototypes).Program; }); c[i] = Measure(() => { var cat = FunctionCatalog.FromSourceIndex(files, overlay); cat.MarkCodeAvailable(prototypes.Select(x => x.FunctionId)); return new object[] { cat, ControlLinker.Link(cat, prototypes).Program }; }); } return new(a.OrderBy(x => x).ElementAt(1), b.OrderBy(x => x).ElementAt(1), c.OrderBy(x => x).ElementAt(1)); }
readonly record struct LegacyRow(string RelativeFile, int StartLine, string FunctionName, bool IsEvent, bool IsMethod, bool IsPri, bool IsLater, bool IsOnly, bool IsSingle, bool LegacyFinalPriority);
readonly record struct LegacyOracle(LegacyRow[] Rows, Dictionary<SemanticFunctionKey, SemanticFunctionMetadata> Overlay);
readonly record struct Retained(long Catalog, long Linked, long Combined);
