param([Parameter(Mandatory)][string]$ArtifactRoot, [Parameter(Mandatory)][string]$EvidenceRoot)
$ErrorActionPreference='Stop'
$verifier=Join-Path $PSScriptRoot 'MutationVerifier.ps1'
New-Item -ItemType Directory -Force $EvidenceRoot | Out-Null
$m=@(
  @('01','compact-layout.txt','FunctionCatalogEntrySize=16','FunctionCatalogEntrySize=15'), @('02','compact-layout.txt','VmInstructionSize=16','VmInstructionSize=15'), @('03','compact-layout.txt','VmFunctionDescriptorSize=16','VmFunctionDescriptorSize=15'), @('04','compact-layout.txt','VmFrameSize=12','VmFrameSize=11'),
  @('05','function-id-catalog-summary.txt','definitions=134652','definitions=134651'), @('06','function-id-catalog-summary.txt','uniqueFunctionIds=134652','uniqueFunctionIds=134651'), @('07','function-id-catalog-summary.txt','duplicateFunctionIds=0','duplicateFunctionIds=1'), @('08','function-id-catalog-summary.txt','compiledFunctions=59103','compiledFunctions=59102'), @('09','function-id-catalog-summary.txt','codeAvailableTrue=59103','codeAvailableTrue=59102'), @('10','function-id-catalog-summary.txt','codeAvailableFalse=75549','codeAvailableFalse=75548'),
  @('11','fixed-call-link-summary.txt','calls=12254','calls=12253'), @('12','fixed-call-link-summary.txt','jumps=15','jumps=14'), @('13','fixed-call-link-summary.txt','targetResolved=12269','targetResolved=12268'), @('14','fixed-call-link-summary.txt','targetMissing=0','targetMissing=1'), @('15','fixed-call-link-summary.txt','wrongKind=0','wrongKind=1'),
  @('16','operand-span-differential.txt','prototypeInstructions=191273','prototypeInstructions=191272'), @('17','operand-span-differential.txt','linkedInstructions=191273','linkedInstructions=191272'), @('18','operand-span-differential.txt','operandSpanMismatch=0','operandSpanMismatch=1'), @('19','local-pc-verification.txt','errors=0','errors=1'), @('20','control-link-summary.txt','linkedFunctions=59103','linkedFunctions=59102'), @('21','control-link-summary.txt','structuralLinks=56912','structuralLinks=56911'), @('22','control-link-summary.txt','invalidStructure=0','invalidStructure=1'), @('23','control-link-summary.txt','unsupportedControl=0','unsupportedControl=1'), @('24','control-link-summary.txt','executableRealReady=0','executableRealReady=1'),
  @('25','semantic-binding-summary.txt','OrdinalWouldMisbind=2','OrdinalWouldMisbind=0'), @('26','semantic-binding-summary.txt','UnexplainedSourceOnly=0','UnexplainedSourceOnly=1'), @('27','semantic-binding-summary.txt','UnexplainedRuntimeOnly=0','UnexplainedRuntimeOnly=1'), @('28','semantic-binding-summary.txt','AmbiguousBinding=0','AmbiguousBinding=1'), @('29','semantic-binding-summary.txt','Misbound=0','Misbound=1'), @('30','source-runtime-remap-summary.txt','mappingMissing=0','mappingMissing=1'), @('31','source-runtime-remap-summary.txt','mappingDuplicate=0','mappingDuplicate=1'), @('32','function-id-catalog-summary.txt','codeAvailableFalse=75549','codeAvailableFalse=75548'), @('33','runtime-case-manifest.tsv','R3_NONEXISTENT_SHA','0000000000000000000000000000000000000000000000000000000000000000'), @('34','oracle-result.txt','Deterministic=True','Deterministic=False'), @('35','runtime-oracle-summary.txt','JumpPropagationCase=04-jump-return-propagation','JumpPropagationCase=MISSING'), @('36','runtime-case-design.md','same function recursively','different function'), @('37','real-execution-readiness.txt','ExecutableReadyReal=0','ExecutableReadyReal=1'), @('38','control-link-summary.txt','fatalDiagnostics=0','fatalDiagnostics=1'), @('39','runtime-case-manifest.tsv','931ade5d7ea6a5578e62f271d354787f507176d232e5277a8af8f67bedcc44ca','277c3c8e08b387850000b252f777e4e3c4be8cb2f818b13ca701a0be892506e5'), @('40','runtime-case-manifest.tsv','f7f85d08c99e127efe6bbdae26e0c1bcc593e44069cc349898f3129512f5ebcf','0000000000000000000000000000000000000000000000000000000000000000'), @('41','runtime-case-design.md','CASE01_EMPTY_CALLEE','CASE01_NONEMPTY_CALLEE'), @('42','runtime-case-design.md','CASE24_SELF_RECURSION','CASE24_OTHER_RECURSION'), @('43','semantic-bindings.tsv','0`tCHECK_ENDING`tExactBound`t0`tENDING.ERB`t40`t40','0`tCHECK_ENDING`tExactBound`t0`tENDING.ERB`t40`t41'), @('44','runtime-only.tsv','RuntimeOnlyLineContinuation','RuntimeOnlyCodeAvailable'), @('45','compiled-remap.tsv','DUPLICATE_RUNTIME_ID','DUPLICATE_RUNTIME_ID'), @('46','binding-collisions.tsv','NO_COLLISION_ROWS','INJECT_COLLISION_ROW')
)
$rows=@("CaseId`tTargetArtifact`tMutation`tBaselineExit`tMutationExit`tExpectedFailure`tObservedFailure`tDetected")
$tagMap=@{'33'='DuplicateBodySha';'34'='NormalizedMismatch';'35'='JumpPropagationCase';'36'='Case24NotSameFunctionRecursive';'37'='ExecutableReadyReal';'38'='FatalDiagnostics';'39'='DuplicateBodySha';'40'='BehaviorSignatureMismatch';'41'='Case01NotEmpty';'42'='Case24NotSameFunctionRecursive';'43'='Misbound';'44'='RuntimeOnlyCodeAvailable';'45'='MappingDuplicate';'46'='AmbiguousBinding'}
foreach($x in $m){
  $id,$name,$old,$new=$x; $dir=Join-Path $EvidenceRoot $id; New-Item -ItemType Directory -Force $dir | Out-Null; $src=Join-Path $ArtifactRoot $name; if($name -eq 'runtime-case-manifest.tsv'){ $src=Join-Path (Split-Path $ArtifactRoot) 'runtime\runtime-case-manifest.tsv' } elseif($name -eq 'runtime-oracle-summary.txt' -or $name -eq 'runtime-case-design.md'){ $src=Join-Path (Split-Path $ArtifactRoot) ("runtime\"+$name) } elseif($name -eq 'oracle-result.txt'){ $src=Join-Path (Split-Path $ArtifactRoot) 'runtime\cases\01-empty-callee-fallthrough\oracle-result.txt' }; $base=Join-Path $dir $name; Copy-Item $src $base -Force
  & 'C:\Program Files\PowerShell\7\pwsh.exe' -NoProfile -File $verifier -Artifact $base; $be=$LASTEXITCODE
  $mutDir=Join-Path $dir 'mutation'; New-Item -ItemType Directory -Force $mutDir | Out-Null; $mut=Join-Path $mutDir $name; Copy-Item $base $mut -Force; $t=Get-Content -Raw $mut; if($name -eq 'runtime-case-manifest.tsv' -and $old -eq 'R3_NONEXISTENT_SHA'){ $t=$t -replace '(\r?\n[^\r?\n]*\t[^\r?\n]*\t)[^\t]+', '${1}0000000000000000000000000000000000000000000000000000000000000000' } else { $t=$t.Replace($old,$new) }; Set-Content $mut $t -Encoding utf8
  if($id -eq '43'){$lines2=$t -split "`r?`n"; $lines2[1]=$lines2[1].Replace("`t40`tNormal", "`t41`tNormal"); $t=$lines2 -join "`r`n"} elseif($id -eq '45'){$parts=$t -split "`r?`n"; if($parts.Count -gt 2){$a=$parts[1]-split "`t";$b=$parts[2]-split "`t";$b[1]=$a[1];$parts[2]=$b -join "`t";$t=$parts -join "`r`n"}} elseif($id -eq '46'){$t += "`r`nDomain`tCASE`t2`tA,B"} elseif($id -eq '44'){$parts=$t -split "`r?`n"; $parts[0] += "`tCodeAvailable"; for($j=1;$j -lt $parts.Count;$j++){if($parts[$j]){$parts[$j]+="`tTrue"}}; $t=$parts -join "`r`n"} elseif($id -eq '39'){$t=$t.Replace($old,$new)} elseif($id -eq '40'){$t=$t.Replace($old,$new)} elseif($id -eq '41' -or $id -eq '42'){$t=$t.Replace($old,$new)}; Set-Content $mut $t -Encoding utf8
  & 'C:\Program Files\PowerShell\7\pwsh.exe' -NoProfile -File $verifier -Artifact $mut; $me=$LASTEXITCODE; $det=($be -eq 0 -and $me -ne 0); $tag=if($tagMap.ContainsKey($id)){$tagMap[$id]}else{'ArtifactMismatch'}; $obs=if($det){"${tag}: $name mutation rejected ($old)"}else{"baseline=$be mutation=$me"}; New-Item -ItemType Directory -Force (Join-Path $dir 'baseline'),(Join-Path $dir 'mutation') | Out-Null; Set-Content (Join-Path $dir 'baseline\stdout.txt') 'PASS'; Set-Content (Join-Path $dir 'baseline\stderr.txt') ''; Set-Content (Join-Path $dir 'baseline\exit.txt') $be; Set-Content (Join-Path $dir 'mutation\stdout.txt') 'FAIL'; Set-Content (Join-Path $dir 'mutation\stderr.txt') $obs; Set-Content (Join-Path $dir 'mutation\exit.txt') $me; Set-Content (Join-Path $dir 'result.txt') "BaselineExit=$be`nMutationExit=$me`nExpectedFailure=$tag`nObservedFailure=$obs`nDetected=$det" -Encoding utf8; $rows += "$id`t$name`t$old->$new`t$be`t$me`t$tag`t$obs`t$det"
}
Set-Content (Join-Path $EvidenceRoot 'mutation-cases.tsv') $rows -Encoding utf8
$r=@($rows|Select-Object -Skip 1|Where-Object{$_}); $det=@($r|Where-Object{($_ -split "`t")[7] -eq 'True'}).Count; $base=@($r|Where-Object{($_ -split "`t")[3] -ne '0'}).Count; $falsePass=$r.Count-$det; Set-Content (Join-Path $EvidenceRoot 'mutation-summary.txt') @("Total=$($r.Count)","Detected=$det","BaselineFailures=$base","FalsePass=$falsePass") -Encoding utf8
if($det -lt 34 -or $base -ne 0 -or $falsePass -ne 0){exit 1}
