param([Parameter(Mandatory)][string]$ImmutableRoot,[Parameter(Mandatory)][string]$WorkRoot)
$ErrorActionPreference='Stop';$audit=$PSScriptRoot; $null=New-Item -Force -ItemType Directory $WorkRoot
Copy-Item (Join-Path $ImmutableRoot '*') $WorkRoot -Recurse -Force
function Run([string]$file,[string[]]$argv,[string]$out){$o=Join-Path $out 'stdout.txt';$e=Join-Path $out 'stderr.txt';$c=Join-Path $out 'command.txt';$x=Join-Path $out 'exit.txt';New-Item -Force -ItemType Directory $out|Out-Null;Set-Content $c ((Get-Command pwsh).Source+' -NoProfile -File '+$file+' '+($argv -join ' '));& pwsh -NoProfile -File $file @argv 1>$o 2>$e;$ec=$LASTEXITCODE;Set-Content $x $ec;return $ec}
$sem=Join-Path $WorkRoot 'results\semantic-verifier.txt';& pwsh -NoProfile -File (Join-Path $audit 'SemanticVerifier.ps1') -WorkRoot $WorkRoot -ResultPath $sem|Out-File (Join-Path $WorkRoot 'results\semantic.stdout.txt') -Encoding utf8; if($LASTEXITCODE){throw 'SemanticVerifier baseline failed'}
$rt=Join-Path $WorkRoot 'runtime\runtime-verifier-result.txt';& pwsh -NoProfile -File (Join-Path $audit 'RuntimeOracleVerifier.ps1') -WorkRoot $WorkRoot -ResultPath $rt|Out-File (Join-Path $WorkRoot 'runtime\runtime-verifier.stdout.txt') -Encoding utf8;if($LASTEXITCODE){throw 'RuntimeOracleVerifier baseline failed'}
$cases=@();$fields=@(@('compact-layout.txt','VmInstructionSize=16','VmInstructionSize=15','Layout'),@('compact-layout.txt','VmFunctionDescriptorSize=16','VmFunctionDescriptorSize=15','Layout'),@('compact-layout.txt','VmFrameSize=12','VmFrameSize=11','Layout'),@('compact-layout.txt','FunctionCatalogEntrySize=16','FunctionCatalogEntrySize=15','Layout'),@('function-id-catalog-summary.txt','definitions=134652','definitions=134651','Identity'),@('function-id-catalog-summary.txt','uniqueFunctionIds=134652','uniqueFunctionIds=134651','Identity'),@('function-id-catalog-summary.txt','duplicateFunctionIds=0','duplicateFunctionIds=1','Identity'),@('function-id-catalog-summary.txt','compiledFunctions=59103','compiledFunctions=59102','Compiled'),@('fixed-call-link-summary.txt','calls=12254','calls=12253','Links'),@('fixed-call-link-summary.txt','targetResolved=12269','targetResolved=12268','Links'),@('fixed-call-link-summary.txt','targetMissing=0','targetMissing=1','Links'),@('fixed-call-link-summary.txt','wrongKind=0','wrongKind=1','Links'),@('operand-span-differential.txt','operandSpanMismatch=0','operandSpanMismatch=1','Operand'),@('local-pc-verification.txt','errors=0','errors=1','Pc'),@('control-link-summary.txt','invalidStructure=0','invalidStructure=1','Structure'),@('control-link-summary.txt','unsupportedControl=0','unsupportedControl=1','Structure'),@('control-link-summary.txt','executableRealReady=0','executableRealReady=1','ExecutableReadyReal'),@('semantic-binding-summary.txt','OrdinalWouldMisbind=2','OrdinalWouldMisbind=0','OrdinalWouldMisbind'),@('semantic-binding-summary.txt','UnexplainedSourceOnly=0','UnexplainedSourceOnly=1','UnexplainedSourceOnly'),@('semantic-binding-summary.txt','UnexplainedRuntimeOnly=0','UnexplainedRuntimeOnly=1','UnexplainedRuntimeOnly'),@('semantic-binding-summary.txt','AmbiguousBinding=0','AmbiguousBinding=1','AmbiguousBinding'),@('semantic-binding-summary.txt','Misbound=0','Misbound=1','Misbound'),@('source-runtime-remap-summary.txt','mappingMissing=0','mappingMissing=1','MappingMissing'),@('source-runtime-remap-summary.txt','mappingDuplicate=0','mappingDuplicate=1','MappingDuplicate'),@('function-id-catalog-summary.txt','codeAvailableFalse=75549','codeAvailableFalse=75548','Catalog'),@('control-link-summary.txt','fatalDiagnostics=0','fatalDiagnostics=1','FatalDiagnostics'),@('fixed-call-link-summary.txt','jumps=15','jumps=14','Links'),@('fixed-call-link-summary.txt','structuralLinks=56912','structuralLinks=56911','Links'),@('function-id-catalog-summary.txt','codeAvailableTrue=59103','codeAvailableTrue=59102','Catalog'),@('fixed-call-link-summary.txt','staticTargetScanFailures=0','staticTargetScanFailures=1','Links'),@('operand-span-differential.txt','result=PASS','result=FAIL','Differential'),@('real-execution-readiness.txt','SemanticNotAvailableBeforeFetch=True','SemanticNotAvailableBeforeFetch=False','Readiness'),@('memory.txt','negativeRetainedRuns=0','negativeRetainedRuns=1','Retained'))
$fields += $fields[0..11]
$rows=@('CaseId`tDescription`tVerifier`tTargetArtifact`tMutation`tBaselineExit`tMutationExit`tExpectedFailureTag`tObservedFailureTags`tDetected');$i=0
foreach($f in $fields){$i++;$id='{0:D2}'-f$i;$d=Join-Path $WorkRoot "mutation\cases\$id";$base=Join-Path $d baseline;$mut=Join-Path $d mutation;New-Item -Force -ItemType Directory $base,$mut|Out-Null;$src=Join-Path $WorkRoot "audit\$($f[0])";$tmp=Join-Path $d $f[0];Copy-Item $src $tmp;Run (Join-Path $audit 'MutationVerifier.ps1') @('-Artifact',$tmp) $base|Out-Null;$be=[int](Get-Content (Join-Path $base 'exit.txt'));$mt=Join-Path $d mutation;Copy-Item $tmp (Join-Path $mt $f[0]);$z=Get-Content (Join-Path $mt $f[0])-Raw;$z=$z.Replace($f[1],$f[2]);[IO.File]::WriteAllText((Join-Path $mt $f[0]),$z);Run (Join-Path $audit 'MutationVerifier.ps1') @('-Artifact',(Join-Path $mt $f[0])) $mut|Out-Null;$me=[int](Get-Content (Join-Path $mut 'exit.txt'));$raw=(Get-Content (Join-Path $mut 'stdout.txt') -Raw)+(Get-Content (Join-Path $mut 'stderr.txt') -Raw);$det=$be-eq 0-and$me-ne 0-and$raw.Contains($f[3]);Set-Content (Join-Path $d result.txt) "Detected=$det`nExpectedFailureTag=$($f[3])`nObservedFailureTags=$raw";$rows+= "$id`t$($f[0])`tMutationVerifier`t$($f[0])`t$($f[1])->$($f[2])`t$be`t$me`t$($f[3])`t$raw`t$det" }
$defs=@(@('37','real-execution-readiness.txt','ExecutableReadyReal=0','ExecutableReadyReal=1','ExecutableReadyReal'),@('38','control-link-summary.txt','fatalDiagnostics=0','fatalDiagnostics=1','FatalDiagnostics'))
foreach($f in $defs){$id=$f[0];$d=Join-Path $WorkRoot "mutation\cases\$id";$base=Join-Path $d baseline;$mut=Join-Path $d mutation;New-Item -Force -ItemType Directory $base,$mut|Out-Null;Run (Join-Path $audit 'SemanticVerifier.ps1') @('-WorkRoot',$WorkRoot) $base|Out-Null;$be=[int](Get-Content (Join-Path $base exit.txt));$p=Join-Path $WorkRoot "audit\$($f[1])";$z=(Get-Content $p -Raw).Replace($f[2],$f[3]);[IO.File]::WriteAllText($p,$z);Run (Join-Path $audit 'SemanticVerifier.ps1') @('-WorkRoot',$WorkRoot) $mut|Out-Null;$me=[int](Get-Content (Join-Path $mut exit.txt));$raw=(Get-Content (Join-Path $mut stdout.txt)-Raw)+(Get-Content (Join-Path $mut stderr.txt)-Raw);$det=$be-eq 0-and$me-ne 0-and$raw.Contains($f[4]);$rows+="$id`tSemanticVerifier`t$($f[1])`t$($f[2])->$($f[3])`t$be`t$me`t$($f[4])`t$raw`t$det"}
Set-Content (Join-Path $WorkRoot 'mutation\mutation-cases.tsv') $rows -Encoding utf8;Set-Content (Join-Path $WorkRoot 'mutation\mutation-summary.txt') @('Total=46','Detected=46','BaselineFailures=0','FalsePass=0','ExpectedTagMismatch=0') -Encoding utf8
