param([Parameter(Mandatory)][string]$WorkRoot,[string]$ResultPath)
$ErrorActionPreference='Stop';$errors=[Collections.Generic.List[string]]::new()
function Fail([string]$tag){if(-not $errors.Contains($tag)){$errors.Add($tag)}}
function Rows([string]$n){$p=Join-Path $WorkRoot "audit\$n";if(!(Test-Path $p)){Fail "Missing:$n";return @()};@(Import-Csv -Delimiter "`t" $p)}
function V([string]$p,[string]$k){if(!(Test-Path $p)){Fail "Missing:$([IO.Path]::GetFileName($p))";return $null};$x=Get-Content $p|?{$_ -like "$k=*"}|select -First 1;if($x){$x.Substring($k.Length+1)}}
$b=Rows semantic-bindings.tsv;$so=Rows source-only.tsv;$ro=Rows runtime-only.tsv;$co=Rows binding-collisions.tsv;$ord=Rows ordinal-would-misbind.tsv;$rm=Rows compiled-remap.tsv;$ln=Rows fixed-call-links.tsv;$ex=@($b|? BindingKind -eq ExactBound)
if($b.Count-ne 134652){Fail IdentityBindingCount};if($ex.Count-ne 134649){Fail ExactBound};if($so.Count-ne 3){Fail SourceOnly};if($ro.Count-ne 3){Fail RuntimeOnly};if($co.Count-ne 0){Fail AmbiguousBinding};if($ord.Count-ne 2){Fail OrdinalWouldMisbind}
$bad=0;foreach($x in $ex){if([string]::IsNullOrWhiteSpace($x.SourceFunctionId)-or$x.SourceFunctionId-eq'-1'-or$x.SourceStartLine-ne$x.RuntimeStartLine){$bad++}};if(@($ex|group SourceFunctionId|?{$_.Count -gt 1}).Count-or@($ex|group RuntimeFunctionId|?{$_.Count -gt 1}).Count){$bad++};if($bad){Fail Misbound}
if($rm.Count-ne 59103){Fail MappingCount};if(@($rm|group RuntimeFunctionId|?{$_.Count -gt 1}).Count-or@($rm|group SourceFunctionId|?{$_.Count -gt 1}).Count){Fail MappingDuplicate};if($ln.Count-ne 12269){Fail FixedLinkCount};if(@($ln|?{$_.Resolved -ne 'True'}).Count){Fail FixedLinkUnresolved};if(@($ln|?{$_.Opcode -eq 'CALL'}).Count-ne 12254-or@($ln|?{$_.Opcode -eq 'JUMP'}).Count-ne 15){Fail FixedLinkOpcodeCount};if(@($ro|?{$_.CodeAvailable -eq 'True'}).Count){Fail RuntimeOnlyCodeAvailable}
$ready=Join-Path $WorkRoot 'audit\real-execution-readiness.txt';if((V $ready ExecutableReadyReal)-ne'0'){Fail ExecutableReadyReal};$s=Join-Path $WorkRoot 'audit\control-link-summary.txt';if((V $s linkedFunctions)-ne'59103'-or(V $s linkedInstructions)-ne'191273'){Fail ControlLinkSummary};if((V $s fatalDiagnostics)-ne'0'){Fail FatalDiagnostics}
foreach($k in 'VmInstructionSize','VmFunctionDescriptorSize','VmFrameSize','FunctionCatalogEntrySize'){if((V (Join-Path $WorkRoot 'audit\compact-layout.txt') $k)-ne(@{VmInstructionSize='16';VmFunctionDescriptorSize='16';VmFrameSize='12';FunctionCatalogEntrySize='16'})[$k]){Fail "Layout:$k"}}
$p=Join-Path $WorkRoot 'phase1';if((Get-Content (Join-Path $p baseline-manifest.sha256)-Raw).Trim() -ne (Get-Content (Join-Path $p current-manifest.sha256)-Raw).Trim()){Fail Phase1ManifestMismatch};$o=Join-Path $WorkRoot 'runtime\runtime-verifier-result.txt';if(!(Test-Path $o)-or(Get-Content $o -Raw)-notmatch 'RuntimeOracleVerifier=PASS'){Fail RuntimeOracleVerifier}
$result=if($errors.Count){'FAIL'}else{'PASS'};$out=@("SemanticVerifier=$result","SourceDefinitions=$($ex.Count+$so.Count)","RuntimeDefinitions=$($ex.Count+$ro.Count)","ExactBound=$($ex.Count)","SourceOnly=$($so.Count)","RuntimeOnly=$($ro.Count)","AmbiguousBinding=$($co.Count)","Misbound=$bad","OrdinalWouldMisbind=$($ord.Count)","CompiledMappings=$($rm.Count)","FixedLinks=$($ln.Count)","FatalDiagnostics=$(V $s fatalDiagnostics)","Errors=$($errors.Count)","ErrorTags=$($errors -join ',')");if($ResultPath){[IO.File]::WriteAllLines($ResultPath,$out,[Text.UTF8Encoding]::new($false))};$out;if($errors.Count){exit 1}
