<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>

    <RootNamespace>MinorShift.Emuera</RootNamespace>
    <Version>0.2.4.4</Version>

    

    <ApplicationIcon>era_v.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>

    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Minimum</AnalysisMode>
    
    <TieredCompilation>false</TieredCompilation>

    
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Forms\ColorBox.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Forms\EraPictureBox.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Enums.NET" Version="4.0.2" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.49-beta">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SkiaSharp" Version="3.0.0-preview.3.1 " />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="3.0.0-preview.3.1 " />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>
</Project>