<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefineConstants Condition="'$(R0F6G10C3)' == 'true'">$(DefineConstants);R0_F6G10C1;R0_F6G10C2;R0_F6G10C3</DefineConstants>
    <DefineConstants Condition="'$(R0F6G10C2)' == 'true'">$(DefineConstants);R0_F6G10C1;R0_F6G10C2</DefineConstants>
    <DefineConstants Condition="'$(R0F6G10C1)' == 'true'">$(DefineConstants);R0_F6G10C1</DefineConstants>
    <DefineConstants Condition="'$(R0E2S)' == 'true'">$(DefineConstants);R0_E2S</DefineConstants>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Minimum</AnalysisMode>
  </PropertyGroup>
</Project>
