import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import path from 'node:path';import fs from 'node:fs';
const root=process.cwd(),handlers=new Map(),wh=new Map();const body={id:'',closest:()=>null},screen={id:'game-screen',closest:s=>s.includes('#game-surface')?{}:null},input={id:'runtime-input',closest:()=>null},toolbar={id:'macro-editor',closest:()=>({})};let focused=true;
globalThis.document={body,activeElement:screen,hidden:false,hasFocus:()=>focused,querySelector:()=>({dataset:{keyMacroReady:'true',pendingKind:'integer',keyMacroEnabled:'true'}}),getElementById:()=>({value:''}),addEventListener:(n,f)=>handlers.set(n,f),removeEventListener:(n)=>handlers.delete(n)};globalThis.window={addEventListener:(n,f)=>wh.set(n,f),removeEventListener:n=>wh.delete(n)};
const m=await import(pathToFileURL(path.resolve(import.meta.dirname,'../Emuera.Web/wwwroot/host-key-macros.js')).href);assert.equal(typeof m.getKeyState,'function','raw state reader required; old host module has no mouse/physical key reader');m.attach({invokeMethodAsync:()=>Promise.resolve()});
const rows=[];const check=(name,values)=>{for(const [k,v]of Object.entries(values))assert.equal(m.getKeyState(Number(k)),v?0x8000:0,name+' vk='+k);rows.push(name);};const key=(code,key,keyCode,down,mods={},repeat=false)=>handlers.get(down?'keydown':'keyup')({code,key,keyCode,target:document.activeElement,shiftKey:false,ctrlKey:false,altKey:false,metaKey:false,...mods,repeat,isComposing:false,cancelable:true,preventDefault(){},stopImmediatePropagation(){}});const mouse=(type,buttons,mods={})=>handlers.get(type)({type,target:screen,buttons,altKey:false,ctrlKey:false,shiftKey:false,...mods});
key('AltLeft','Alt',18,true,{altKey:true});check('left Alt',{18:1,164:1,165:0});key('AltRight','Alt',18,true,{altKey:true});check('two Alt',{18:1,164:1,165:1});key('AltLeft','Alt',18,false,{altKey:true});check('right remains after left release',{18:1,164:0,165:1});key('AltRight','Alt',18,false);check('released',{18:0,164:0,165:0});
for(const [left,right,vk,group]of [['ShiftLeft','ShiftRight',160,16],['ControlLeft','ControlRight',162,17]]){const keyName=group===16?'Shift':'Control',mod=group===16?{shiftKey:true}:{ctrlKey:true};key(left,keyName,group,true,mod);key(right,keyName,group,true,mod);key(left,keyName,group,false,mod);check('dual '+keyName,{[vk]:0,[vk+1]:1,[group]:1});key(right,keyName,group,false);}
document.activeElement=input;key('KeyA','a',65,true);check('ordinary input held A',{65:1});check('repeat query no consumption',{65:1});handlers.get('focusout')({target:input,relatedTarget:null});document.activeElement=body;check('input DOM removal keeps held key while page remains focused',{65:1});document.activeElement=input;key('KeyA','a',65,false);check('ordinary input release',{65:0});key('KeyA','a',65,true);key('KeyA','a',65,false);check('short pulse not retained',{65:0});
mouse('mousedown',31);check('all five mouse buttons',{1:1,2:1,4:1,5:1,6:1});mouse('mouseup',0);check('mouse release',{1:0,2:0,4:0,5:0,6:0});mouse('mousedown',0,{altKey:true});check('mouse carries generic Alt but does not invent left/right',{18:1,164:0,165:0});mouse('mouseup',0);
key('KeyA','a',65,true);handlers.get('focusout')({relatedTarget:screen});document.activeElement=screen;check('valid input to screen retains actual held state',{65:1});key('KeyA','a',65,false);check('release after valid focus switch',{65:0});key('KeyA','a',65,true);wh.get('blur')();focused=false;check('blur clears',{65:0});focused=true;key('KeyA','a',65,true,{},true);check('repeat after re-focus cannot recreate stale hold',{65:0});key('KeyA','a',65,false);key('KeyA','a',65,true);check('new physical press after focus',{65:1});document.hidden=true;handlers.get('visibilitychange')();document.hidden=false;check('tab switch clears',{65:0});
key('KeyA','a',65,true);handlers.get('compositionstart')();check('IME clears state',{65:0});handlers.get('compositionend')();check('IME end does not restore old hold',{65:0});document.activeElement=toolbar;key('KeyA','a',65,true);check('other editor ignored',{65:0});document.activeElement=screen;check('out of range',{256:0,'-1':0});mouse('mousedown',31);handlers.get('mouseup')({type:'mouseup',target:toolbar,buttons:0});check('release outside surface clears all mouse buttons',{1:0,2:0,4:0,5:0,6:0});m.detach();check('detach clears',{65:0});
if(process.argv[2]){assert.ok(!fs.existsSync(process.argv[2]),'preserve evidence');fs.writeFileSync(process.argv[2],JSON.stringify({status:'PASS',checks:rows.length,rows,scope:'actual host module listeners with task-only DOM stand-in; physical OS events not proved'},null,2));}console.log('PASS raw key/mouse/focus unit '+rows.length);
