import assert from 'node:assert/strict';import{test}from'node:test';import{pathToFileURL}from'node:url';import path from'node:path';
const m=await import(pathToFileURL(path.resolve(import.meta.dirname,'../Emuera.Web/wwwroot/host-key-macros.js')));
class Events { listeners=new Map(); addEventListener(t,f){const a=this.listeners.get(t)||[];a.push(f);this.listeners.set(t,a)}removeEventListener(t,f){this.listeners.set(t,(this.listeners.get(t)||[]).filter(x=>x!==f))}fire(t,e){for(const f of this.listeners.get(t)||[])f(e)}}
const doc=new Events(),win=new Events();globalThis.document=doc;globalThis.window=win;doc.body={};doc.hidden=false;let focused=true;doc.hasFocus=()=>focused;
const input={id:'runtime-input',value:'(H\\e\\nd\\e\\n)*10'};doc.activeElement=input;const state={keyMacroEnabled:'true',keyMacroReady:'true',pendingKind:'string',requestId:'1',sessionGeneration:'1'};doc.querySelector=()=>({dataset:state});doc.getElementById=()=>input;const calls=[];const host={invokeMethodAsync:(...a)=>{calls.push(a);return Promise.resolve()}};
function key(code,opts={}){const e={code,key:code,repeat:false,cancelable:true,ctrlKey:false,shiftKey:false,altKey:false,metaKey:false,isComposing:false,...opts,preventDefault(){this.prevented=true},stopImmediatePropagation(){this.stopped=true}};doc.fire('keydown',e);return e}
test('F1-F12 call, Shift register and Ctrl top/numpad group share one host event',()=>{m.attach(host);for(let f=1;f<=12;f++){assert.ok(key('F'+f).prevented);assert.equal(calls.at(-1)[8],'recall');key('F'+f,{shiftKey:true});assert.equal(calls.at(-1)[8],'register')}for(let g=0;g<10;g++){key('Digit'+g,{ctrlKey:true});assert.equal(calls.at(-1)[8],'group');assert.equal(calls.at(-1)[9],g);key('Numpad'+g,{ctrlKey:true,key:String(g)});assert.equal(calls.at(-1)[9],g)}assert.equal(calls.filter(c=>c[0]==='DispatchHostKey').length,44)});
test('ordinary keys and unsupported modified F not suppressed, repeated macros not dispatched',()=>{let n=calls.length;assert.ok(!key('KeyA',{key:'a'}).prevented);assert.ok(!key('F5',{ctrlKey:true}).prevented);assert.ok(key('F5',{repeat:true}).prevented);assert.equal(calls.length,n)});
test('primitive priority forwards F, shift F, ctrl digit, Tab and Backspace without macro action',()=>{state.pendingKind='mousekey';for(const [code,o]of[['F5',{}],['F1',{shiftKey:true}],['Digit2',{ctrlKey:true}],['Tab',{}],['Backspace',{}]]){assert.ok(key(code,o).prevented);assert.equal(calls.at(-1)[8],'game')}state.pendingKind='string'});
test('IME, hidden tab, no page focus, editor, blur and repeat after focus move',()=>{const n=calls.length;assert.ok(!key('F5',{isComposing:true}).prevented);assert.ok(!key('F5',{keyCode:229}).prevented);doc.hidden=true;assert.ok(!key('F5').prevented);doc.hidden=false;focused=false;assert.ok(!key('F5').prevented);focused=true;doc.activeElement={closest:()=>true};assert.ok(!key('F5').prevented);doc.activeElement=input;assert.equal(calls.length,n);key('F3');const token=calls.at(-1).at(-1);win.fire('blur',{});assert.ok(!m.current(token));let count=calls.length;key('F3',{repeat:true});assert.equal(calls.length,count);doc.fire('compositionstart',{});assert.ok(!key('F3').prevented);doc.fire('compositionend',{})});
test('reattach and detach dispose handlers, no duplicate events',()=>{m.attach(host);let n=calls.filter(c=>c[0]==='DispatchHostKey').length;key('F1');assert.equal(calls.filter(c=>c[0]==='DispatchHostKey').length,n+1);m.detach();assert.ok(!key('F1').prevented)});
test('WAIT defaults suppressed only for keys accepted by the existing game handler',()=>{m.attach(host);const target={closest:()=>true};state.pendingKind='anykey';const n=calls.length;assert.ok(key('Space',{key:' ',target}).prevented);assert.ok(!key('F2',{ctrlKey:true,target}).prevented);assert.ok(!key('Tab',{target}).prevented);assert.ok(!key('KeyL',{metaKey:true,target}).prevented);assert.equal(calls.length,n);state.pendingKind='enter';assert.ok(key('Enter',{key:'Enter',target}).prevented);assert.ok(!key('Space',{key:' ',target}).prevented);state.pendingKind='string';m.detach()});
test('versioned origin/game/profile settings persist whole bank; missing/corrupt/quota are explicit',()=>{const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},slots=Array(120).fill('');slots[119]='END';assert.equal(m.save('game','p',9,slots,storage),'保存しました');assert.equal(m.load('game','p',storage).slots[119],'END');assert.equal(m.load('game','other',storage).group,0);storage.setItem=[].push;const denied={getItem(){throw Error('blocked')},setItem(){throw Error('quota')}};assert.match(m.save('g','p',0,slots,denied),/未保存/);assert.match(m.load('g','p',denied).message,/読めません/);const corrupt={getItem:()=>'{bad'};assert.match(m.load('g','p',corrupt).message,/読めません/);const wrong={getItem:()=>JSON.stringify({version:99,group:0,slots})};assert.match(m.load('g','p',wrong).message,/読めません/)});
test('macro.txt whole replacement preserves old data on failed atomic storage; v1 migration and game/profile isolation',()=>{
 const data=new Map(),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)},slots=Array(120).fill(''),names=Array.from({length:10},(_,g)=>'日本語名称:'+g);
 slots[119]='  コロン: \\e\\n  ';assert.ok(m.replace('g','p',7,slots,names,storage).saved);const before=JSON.stringify([...data]);
 assert.deepEqual(m.load('g','p',storage).groupNames,names);assert.equal(m.load('g','p',storage).slots[119],slots[119]);
 const denied={getItem:storage.getItem,setItem(){throw Error('quota')}};assert.equal(m.replace('g','p',0,Array(120).fill('new'),names,denied).saved,false);assert.equal(JSON.stringify([...data]),before);
 assert.equal(m.replace('g','p',0,['bad'],names,storage).saved,false);assert.equal(JSON.stringify([...data]),before);
 assert.equal(m.load('other','p',storage).slots[119],'');assert.equal(m.load('g','other',storage).slots[119],'');
 const old={getItem:()=>JSON.stringify({version:1,group:3,slots})};const migrated=m.load('g','p',old);assert.equal(migrated.slots[119],slots[119]);assert.equal(migrated.group,3);assert.equal(migrated.groupNames[0],'マクログループ0に設定');
});
