<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>EmueraWebPackager</AssemblyName>
    <RuntimeFrameworkVersion>10.0.12</RuntimeFrameworkVersion><Version>1.0.5</Version>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Core/EmueraWebPackager.Core.csproj" /></ItemGroup>
</Project>
