//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorShift.Emuera.UI.Framework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinorShift.Emuera.UI.Framework.FormLocalization", typeof(FormLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConfigDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfigDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※Changes won&apos;t take effect until restart.
        /// </summary>
        internal static string ConfigDialog_ChangeWontTakeEffectUntilRestart {
            get {
                return ResourceManager.GetString("ConfigDialog_ChangeWontTakeEffectUntilRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        internal static string ConfigDialog_Compatibility {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TOSTR automatically for user function arguments.
        /// </summary>
        internal static string ConfigDialog_Compatibility_AutoTOSTR {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_AutoTOSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproduce non-button wrapping like in pre ver1739.
        /// </summary>
        internal static string ConfigDialog_Compatibility_ButtonWarp {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_ButtonWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow CALL on event functions.
        /// </summary>
        internal static string ConfigDialog_Compatibility_CallEvent {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_CallEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Emuera default.
        /// </summary>
        internal static string ConfigDialog_Compatibility_EmueraStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EmueraStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imitate behavior of pseudo-variable RAND from eramaker.
        /// </summary>
        internal static string ConfigDialog_Compatibility_EramakerRAND {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EramakerRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to eramaker default.
        /// </summary>
        internal static string ConfigDialog_Compatibility_EramakerStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EramakerStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate TIMES like in eramaker.
        /// </summary>
        internal static string ConfigDialog_Compatibility_EramakerTIMES {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EramakerTIMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute even if lines cannot be interpreted.
        /// </summary>
        internal static string ConfigDialog_Compatibility_ExecuteErrorLine {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_ExecuteErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use NAME if CALLNAME is empty.
        /// </summary>
        internal static string ConfigDialog_Compatibility_NameForCallname {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_NameForCallname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ignore case for functions and attributes.
        /// </summary>
        internal static string ConfigDialog_Compatibility_NoIgnoreCase {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_NoIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow omission of all arguments when calling user functions.
        /// </summary>
        internal static string ConfigDialog_Compatibility_OmitArgs {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_OmitArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow SP characters.
        /// </summary>
        internal static string ConfigDialog_Compatibility_UseSPCharacters {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_UseSPCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※Many things work differently between Emuera and eramaker,
        ///As well as between older and newer Emuera versions,
        ///These options should solve compatibility problems.
        ///Please don&apos;t change anything if there&apos;s no issues..
        /// </summary>
        internal static string ConfigDialog_Compatibility_Warning {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string ConfigDialog_Debug {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display eramaker compatibility warning.
        /// </summary>
        internal static string ConfigDialog_Debug_CompatibilityWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_CompatibilityWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set for developers.
        /// </summary>
        internal static string ConfigDialog_Debug_DeveloperStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_DeveloperStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to deal with calling non-existing functions.
        /// </summary>
        internal static string ConfigDialog_Debug_FuncNotFoundWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_FuncNotFoundWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore functions that were not called.
        /// </summary>
        internal static string ConfigDialog_Debug_IgnoreUnusedFuncs {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_IgnoreUnusedFuncs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display files that are being loaded at start.
        /// </summary>
        internal static string ConfigDialog_Debug_LoadingReport {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_LoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set for users.
        /// </summary>
        internal static string ConfigDialog_Debug_PlayerStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_PlayerStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse arguments when debug.
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs_Always {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs_Never {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When updated.
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs_OnUpdate {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs_OnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to deal with never called functions.
        /// </summary>
        internal static string ConfigDialog_Debug_UnusedFuncWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_UnusedFuncWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum warning level display.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0:Non-standard grammar.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level0 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:Possible to ignore errors.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level1 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2:Critical errors.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level2 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3:Fatal error.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level3 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_Always {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore them.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_Ignore {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only one per file.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_OncePerFile {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_OncePerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only total number of them.
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_TotalNumber {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_TotalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ConfigDialog_Display {
            get {
                return ResourceManager.GetString("ConfigDialog_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t break lines in the middle buttons.
        /// </summary>
        internal static string ConfigDialog_Display_ButtonWrap {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_ButtonWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames per second.
        /// </summary>
        internal static string ConfigDialog_Display_FPS {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of characters in PRINTC.
        /// </summary>
        internal static string ConfigDialog_Display_PrintCLength {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_PrintCLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of PRINTC per column.
        /// </summary>
        internal static string ConfigDialog_Display_PrintCPerLine {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_PrintCPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Interface.
        /// </summary>
        internal static string ConfigDialog_Display_TextDrawingMode {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_TextDrawingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the background color of buttons when hovering over it.
        /// </summary>
        internal static string ConfigDialog_Display_UseButtonFocusColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_UseButtonFocusColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string ConfigDialog_Environment {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple instances.
        /// </summary>
        internal static string ConfigDialog_Environment_AllowMultipleInstances {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_AllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make autosave.
        /// </summary>
        internal static string ConfigDialog_Environment_AutoSave {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string ConfigDialog_Environment_Browse {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds for infinite loop warn.
        /// </summary>
        internal static string ConfigDialog_Environment_InfiniteLoopAlertTime {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_InfiniteLoopAlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines in history log.
        /// </summary>
        internal static string ConfigDialog_Environment_MaxLog {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_MaxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of used save slots.
        /// </summary>
        internal static string ConfigDialog_Environment_SaveDataPerPage {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_SaveDataPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated text editor.
        /// </summary>
        internal static string ConfigDialog_Environment_TextEditor {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line suffix.
        /// </summary>
        internal static string ConfigDialog_Environment_TextEditorCommandline {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_TextEditorCommandline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Setting.
        /// </summary>
        internal static string ConfigDialog_Environment_TextEditorCommandline_UserSetting {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_TextEditorCommandline_UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow debug commands.
        /// </summary>
        internal static string ConfigDialog_Environment_UseDebugCommand {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseDebugCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use keyboard macros.
        /// </summary>
        internal static string ConfigDialog_Environment_UseKeyMacro {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseKeyMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu.
        /// </summary>
        internal static string ConfigDialog_Environment_UseMenu {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use mouse.
        /// </summary>
        internal static string ConfigDialog_Environment_UseMouse {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use sav folder for save data.
        /// </summary>
        internal static string ConfigDialog_Environment_UseSaveFolder {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string ConfigDialog_Font {
            get {
                return ResourceManager.GetString("ConfigDialog_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string ConfigDialog_Font_BackgroundColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name.
        /// </summary>
        internal static string ConfigDialog_Font_FontName {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string ConfigDialog_Font_FontSize {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected letters.
        /// </summary>
        internal static string ConfigDialog_Font_HighlightColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance between lines.
        /// </summary>
        internal static string ConfigDialog_Font_LineHeight {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Letter.
        /// </summary>
        internal static string ConfigDialog_Font_LogHistoryColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_LogHistoryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Color.
        /// </summary>
        internal static string ConfigDialog_Font_TextColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ConfigDialog_Save {
            get {
                return ResourceManager.GetString("ConfigDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Restart.
        /// </summary>
        internal static string ConfigDialog_SaveAndRestart {
            get {
                return ResourceManager.GetString("ConfigDialog_SaveAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ConfigDialog_System {
            get {
                return ResourceManager.GetString("ConfigDialog_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal language used.
        /// </summary>
        internal static string ConfigDialog_System_ANSI {
            get {
                return ResourceManager.GetString("ConfigDialog_System_ANSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn when multiple non-event functions use same name.
        /// </summary>
        internal static string ConfigDialog_System_DuplicateFuncWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_System_DuplicateFuncWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore capitalization.
        /// </summary>
        internal static string ConfigDialog_System_IgnoreCase {
            get {
                return ResourceManager.GetString("ConfigDialog_System_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search files in subfolders.
        /// </summary>
        internal static string ConfigDialog_System_SearchSubfolder {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SearchSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load files in name-order.
        /// </summary>
        internal static string ConfigDialog_System_SortFileNames {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SortFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to override system functions.
        /// </summary>
        internal static string ConfigDialog_System_SystemFuncOverride {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SystemFuncOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn about overridden functions.
        /// </summary>
        internal static string ConfigDialog_System_SystemFuncOverrideWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SystemFuncOverrideWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use _Rename.csv file.
        /// </summary>
        internal static string ConfigDialog_System_UseRename {
            get {
                return ResourceManager.GetString("ConfigDialog_System_UseRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use _Replace.csv file.
        /// </summary>
        internal static string ConfigDialog_System_UseReplace {
            get {
                return ResourceManager.GetString("ConfigDialog_System_UseReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※If you change system settings,
        ///ERB scripts may not work properly..
        /// </summary>
        internal static string ConfigDialog_System_Warning {
            get {
                return ResourceManager.GetString("ConfigDialog_System_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include full-width space in whitespace.
        /// </summary>
        internal static string ConfigDialog_System_WSIncludesFullWidth {
            get {
                return ResourceManager.GetString("ConfigDialog_System_WSIncludesFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System2.
        /// </summary>
        internal static string ConfigDialog_System2 {
            get {
                return ResourceManager.GetString("ConfigDialog_System2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t process triple symbols inside FORM.
        /// </summary>
        internal static string ConfigDialog_System2_IgnoreTripleSymbol {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_IgnoreTripleSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t autocomplete arguments in character variables.
        /// </summary>
        internal static string ConfigDialog_System2_NoAutoCompleteCVar {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_NoAutoCompleteCVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use binary format for save data.
        /// </summary>
        internal static string ConfigDialog_System2_SaveInBinary {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_SaveInBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use UTF-8 format for save data (only in non-binary).
        /// </summary>
        internal static string ConfigDialog_System2_SaveInUTF8 {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_SaveInUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use new fast random number algorithm.
        /// </summary>
        internal static string ConfigDialog_System2_UseNewRandom {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_UseNewRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable VAR-based instructions.
        /// </summary>
        internal static string ConfigDialog_System2_UseScopedVariableInstruction {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_UseScopedVariableInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ConfigDialog_Title {
            get {
                return ResourceManager.GetString("ConfigDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string ConfigDialog_Window {
            get {
                return ResourceManager.GetString("ConfigDialog_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changeable Window Height.
        /// </summary>
        internal static string ConfigDialog_Window_ChangeableWindowHeight {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_ChangeableWindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get present Window Position.
        /// </summary>
        internal static string ConfigDialog_Window_GetWindowPos {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_GetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Window Size.
        /// </summary>
        internal static string ConfigDialog_Window_GetWindowSize {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_GetWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines per Scroll.
        /// </summary>
        internal static string ConfigDialog_Window_LinesPerScroll {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_LinesPerScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix starting position.
        /// </summary>
        internal static string ConfigDialog_Window_SetWindowPos {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_SetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked Window Height.
        /// </summary>
        internal static string ConfigDialog_Window_WindowHeight {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize window at start.
        /// </summary>
        internal static string ConfigDialog_Window_WindowMaximixed {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowMaximixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Width.
        /// </summary>
        internal static string ConfigDialog_Window_WindowWidth {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Window Position X.
        /// </summary>
        internal static string ConfigDialog_Window_WindowX {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Window Position Y.
        /// </summary>
        internal static string ConfigDialog_Window_WindowY {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ContextMenu_Cut {
            get {
                return ResourceManager.GetString("ContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string ContextMenu_Execute {
            get {
                return ResourceManager.GetString("ContextMenu_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string ContextMenu_KeyMacro {
            get {
                return ResourceManager.GetString("ContextMenu_KeyMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Group.
        /// </summary>
        internal static string ContextMenu_KeyMacroGroup {
            get {
                return ResourceManager.GetString("ContextMenu_KeyMacroGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0}.
        /// </summary>
        internal static string ContextMenu_KeyMacroGroup_Group {
            get {
                return ResourceManager.GetString("ContextMenu_KeyMacroGroup_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ContextMenu_Paste {
            get {
                return ResourceManager.GetString("ContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Clipboard(&amp;C).
        /// </summary>
        internal static string CopyLogToClipboard {
            get {
                return ResourceManager.GetString("CopyLogToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show debug window on the foreground.
        /// </summary>
        internal static string DebugConfigDialog_AlwaysOnTop {
            get {
                return ResourceManager.GetString("DebugConfigDialog_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugConfigDialog_Name {
            get {
                return ResourceManager.GetString("DebugConfigDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug window on start.
        /// </summary>
        internal static string DebugConfigDialog_OpenDebugWindowOnStartup {
            get {
                return ResourceManager.GetString("DebugConfigDialog_OpenDebugWindowOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current window size.
        /// </summary>
        internal static string DebugConfigDialog_SetWindowPos {
            get {
                return ResourceManager.GetString("DebugConfigDialog_SetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigDialog.
        /// </summary>
        internal static string DebugConfigDialog_Title {
            get {
                return ResourceManager.GetString("DebugConfigDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※These options are related to debug window
        ///Settings apply only at start.
        /// </summary>
        internal static string DebugConfigDialog_Warning {
            get {
                return ResourceManager.GetString("DebugConfigDialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window height.
        /// </summary>
        internal static string DebugConfigDialog_WindowHeight {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window width.
        /// </summary>
        internal static string DebugConfigDialog_WindowWidth {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in X.
        /// </summary>
        internal static string DebugConfigDialog_WindowX {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in Y.
        /// </summary>
        internal static string DebugConfigDialog_WindowY {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string DebugDialog_Close {
            get {
                return ResourceManager.GetString("DebugDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string DebugDialog_Console {
            get {
                return ResourceManager.GetString("DebugDialog_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load watch list.
        /// </summary>
        internal static string DebugDialog_File_LoadWatchList {
            get {
                return ResourceManager.GetString("DebugDialog_File_LoadWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save watch list.
        /// </summary>
        internal static string DebugDialog_File_SaveWatchList {
            get {
                return ResourceManager.GetString("DebugDialog_File_SaveWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings(&amp;C).
        /// </summary>
        internal static string DebugDialog_Setting {
            get {
                return ResourceManager.GetString("DebugDialog_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config(&amp;C).
        /// </summary>
        internal static string DebugDialog_Setting_Config {
            get {
                return ResourceManager.GetString("DebugDialog_Setting_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        internal static string DebugDialog_StackTrace {
            get {
                return ResourceManager.GetString("DebugDialog_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay On Top.
        /// </summary>
        internal static string DebugDialog_StayOnTop {
            get {
                return ResourceManager.GetString("DebugDialog_StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emuera - DebugDialog.
        /// </summary>
        internal static string DebugDialog_Title {
            get {
                return ResourceManager.GetString("DebugDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data.
        /// </summary>
        internal static string DebugDialog_UpdateData {
            get {
                return ResourceManager.GetString("DebugDialog_UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Watch.
        /// </summary>
        internal static string DebugDialog_VariableWatch {
            get {
                return ResourceManager.GetString("DebugDialog_VariableWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string DebugDialog_VariableWatch_Object {
            get {
                return ResourceManager.GetString("DebugDialog_VariableWatch_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DebugDialog_VariableWatch_Value {
            get {
                return ResourceManager.GetString("DebugDialog_VariableWatch_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G{0}:Macro Key F{1}:.
        /// </summary>
        internal static string KeyMacro_GMacroKeyF {
            get {
                return ResourceManager.GetString("KeyMacro_GMacroKeyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Key F{0}:.
        /// </summary>
        internal static string KeyMacro_MacroKeyF {
            get {
                return ResourceManager.GetString("KeyMacro_MacroKeyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to macro group {0}.
        /// </summary>
        internal static string KeyMacro_SetMacroGroup {
            get {
                return ResourceManager.GetString("KeyMacro_SetMacroGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Title Screen(&amp;T).
        /// </summary>
        internal static string MainWindow_BackToTitle {
            get {
                return ResourceManager.GetString("MainWindow_BackToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug(&amp;D).
        /// </summary>
        internal static string MainWindow_Debug {
            get {
                return ResourceManager.GetString("MainWindow_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close(&amp;X).
        /// </summary>
        internal static string MainWindow_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(&amp;F).
        /// </summary>
        internal static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERB file.
        /// </summary>
        internal static string MainWindow_FileFilter {
            get {
                return ResourceManager.GetString("MainWindow_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language(&amp;L).
        /// </summary>
        internal static string MainWindow_Language {
            get {
                return ResourceManager.GetString("MainWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Debug widow.
        /// </summary>
        internal static string MainWindow_OpenDebugWindow {
            get {
                return ResourceManager.GetString("MainWindow_OpenDebugWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Code(&amp;C).
        /// </summary>
        internal static string MainWindow_ReloadAllScripts {
            get {
                return ResourceManager.GetString("MainWindow_ReloadAllScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Folder(&amp;F).
        /// </summary>
        internal static string MainWindow_ReloadFolder {
            get {
                return ResourceManager.GetString("MainWindow_ReloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload File(&amp;A).
        /// </summary>
        internal static string MainWindow_ReloadScriptFile {
            get {
                return ResourceManager.GetString("MainWindow_ReloadScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart(&amp;R).
        /// </summary>
        internal static string MainWindow_Restart {
            get {
                return ResourceManager.GetString("MainWindow_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log...(&amp;S).
        /// </summary>
        internal static string MainWindow_SaveLog {
            get {
                return ResourceManager.GetString("MainWindow_SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings(&amp;C).
        /// </summary>
        internal static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Window Width Lock.
        /// </summary>
        internal static string MainWindow_ToggleWidthLock {
            get {
                return ResourceManager.GetString("MainWindow_ToggleWidthLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MainWindow_Tools {
            get {
                return ResourceManager.GetString("MainWindow_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the clipboard because of an unexpected error.
        /// </summary>
        internal static string MessageBox_CanNotOpenClipboard {
            get {
                return ResourceManager.GetString("MessageBox_CanNotOpenClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot return to title during Analysis.
        /// </summary>
        internal static string MessageBox_CanNotReturnToTitle {
            get {
                return ResourceManager.GetString("MessageBox_CanNotReturnToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー発生時はこの機能は使えません.
        /// </summary>
        internal static string MessageBox_CanNotUseWhenError {
            get {
                return ResourceManager.GetString("MessageBox_CanNotUseWhenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期化中はこの機能は使えません.
        /// </summary>
        internal static string MessageBox_CanNotUseWhenInitialize {
            get {
                return ResourceManager.GetString("MessageBox_CanNotUseWhenInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log file can be saved only in the directory below the executable file.
        /// </summary>
        internal static string MessageBox_CanOnlyOutputToSubDirectory {
            get {
                return ResourceManager.GetString("MessageBox_CanOnlyOutputToSubDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Error.
        /// </summary>
        internal static string MessageBox_ConfigError {
            get {
                return ResourceManager.GetString("MessageBox_ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the config file.
        ///Quit Emuera?.
        /// </summary>
        internal static string MessageBox_ConfigFileError {
            get {
                return ResourceManager.GetString("MessageBox_ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Transfer.
        /// </summary>
        internal static string MessageBox_DataTransfer {
            get {
                return ResourceManager.GetString("MessageBox_DataTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Transfer Failure.
        /// </summary>
        internal static string MessageBox_DataTransferFailure {
            get {
                return ResourceManager.GetString("MessageBox_DataTransferFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot return to the title due to an error found in Analysis mode.
        /// </summary>
        internal static string MessageBox_ErrorInAnalysisMode {
            get {
                return ResourceManager.GetString("MessageBox_ErrorInAnalysisMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MessageBox_Exit {
            get {
                return ResourceManager.GetString("MessageBox_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the Game?.
        /// </summary>
        internal static string MessageBox_ExitAsk {
            get {
                return ResourceManager.GetString("MessageBox_ExitAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datフォルダーの作成に失敗しました.
        /// </summary>
        internal static string MessageBox_FailedCreateDataFolder {
            get {
                return ResourceManager.GetString("MessageBox_FailedCreateDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create sav folder.
        /// </summary>
        internal static string MessageBox_FailedCreateSavFolder {
            get {
                return ResourceManager.GetString("MessageBox_FailedCreateSavFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move sav files.
        /// </summary>
        internal static string MessageBox_FailedMoveSavFiles {
            get {
                return ResourceManager.GetString("MessageBox_FailedMoveSavFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log output failed.
        /// </summary>
        internal static string MessageBox_FailedOutputLog {
            get {
                return ResourceManager.GetString("MessageBox_FailedOutputLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log output has been failed.
        /// </summary>
        internal static string MessageBox_FailedOutputLogError {
            get {
                return ResourceManager.GetString("MessageBox_FailedOutputLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Format Error.
        /// </summary>
        internal static string MessageBox_FileFormatError {
            get {
                return ResourceManager.GetString("MessageBox_FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string MessageBox_FileNotFound {
            get {
                return ResourceManager.GetString("MessageBox_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Creation Failure.
        /// </summary>
        internal static string MessageBox_FolderCreationFailure {
            get {
                return ResourceManager.GetString("MessageBox_FolderCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal Font.
        /// </summary>
        internal static string MessageBox_IllegalFont {
            get {
                return ResourceManager.GetString("MessageBox_IllegalFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An illegal font was detected during the Emuera display processing.
        ///The drawing process cannot continue and will be terminated..
        /// </summary>
        internal static string MessageBox_IllegalFontError {
            get {
                return ResourceManager.GetString("MessageBox_IllegalFontError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a possibility of an infinite loop.
        /// </summary>
        internal static string MessageBox_InfiniteLoop {
            get {
                return ResourceManager.GetString("MessageBox_InfiniteLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read files that aren&apos;t .ERB.
        /// </summary>
        internal static string MessageBox_IsNotErb {
            get {
                return ResourceManager.GetString("MessageBox_IsNotErb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The line height will be interpreted the same as the font size due to it being smaller..
        /// </summary>
        internal static string MessageBox_LineHeightLessThanFontSize {
            get {
                return ResourceManager.GetString("MessageBox_LineHeightLessThanFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sav folder exists but couldn&apos;t be found.
        ///Was it deleted?.
        /// </summary>
        internal static string MessageBox_MissingSavFolder {
            get {
                return ResourceManager.GetString("MessageBox_MissingSavFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings couldn&apos;t be changed due to them being fixed by _fixed.config.
        /// </summary>
        internal static string MessageBox_NotAllowChangeSetting {
            get {
                return ResourceManager.GetString("MessageBox_NotAllowChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available during script operation.
        /// </summary>
        internal static string MessageBox_NotAvailableDuringScript {
            get {
                return ResourceManager.GetString("MessageBox_NotAvailableDuringScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Files.
        /// </summary>
        internal static string MessageBox_ReloadErb {
            get {
                return ResourceManager.GetString("MessageBox_ReloadErb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to Load the ERB Files?.
        /// </summary>
        internal static string MessageBox_ReloadErbAsk {
            get {
                return ResourceManager.GetString("MessageBox_ReloadErbAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Replace.csv Error.
        /// </summary>
        internal static string MessageBox_ReplaceError {
            get {
                return ResourceManager.GetString("MessageBox_ReplaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with _Replace.csv file.
        ///Quit Emuera?.
        /// </summary>
        internal static string MessageBox_ReplaceFileError {
            get {
                return ResourceManager.GetString("MessageBox_ReplaceFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string MessageBox_Restart {
            get {
                return ResourceManager.GetString("MessageBox_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the Game?.
        /// </summary>
        internal static string MessageBox_RestartAsk {
            get {
                return ResourceManager.GetString("MessageBox_RestartAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Title.
        /// </summary>
        internal static string MessageBox_ReturnToTitle {
            get {
                return ResourceManager.GetString("MessageBox_ReturnToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Title Screen?.
        /// </summary>
        internal static string MessageBox_ReturnToTitleAsk {
            get {
                return ResourceManager.GetString("MessageBox_ReturnToTitleAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sav folder has been created.
        ///Would you like to move the save data there?.
        /// </summary>
        internal static string MessageBox_SavFolderCreated {
            get {
                return ResourceManager.GetString("MessageBox_SavFolderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of save data to display exceeds the limit (More than 80)..
        /// </summary>
        internal static string MessageBox_TooLargeDisplaySaveData {
            get {
                return ResourceManager.GetString("MessageBox_TooLargeDisplaySaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently {1} line at {0} is being executed.
        ///Since the last input {3} milliseconds has passed and the line was executed {2} times.
        ///Would you like to forcibly terminate processing?.
        /// </summary>
        internal static string MessageBox_TooLongLoop {
            get {
                return ResourceManager.GetString("MessageBox_TooLongLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of save data to display is too small (Less than 20)..
        /// </summary>
        internal static string MessageBox_TooSmallDisplaySaveData {
            get {
                return ResourceManager.GetString("MessageBox_TooSmallDisplaySaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size is too small (Less than 8)..
        /// </summary>
        internal static string MessageBox_TooSmallFontSize {
            get {
                return ResourceManager.GetString("MessageBox_TooSmallFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log size is too small (Less than 500)..
        /// </summary>
        internal static string MessageBox_TooSmallLogSize {
            get {
                return ResourceManager.GetString("MessageBox_TooSmallLogSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Change Setting.
        /// </summary>
        internal static string MessageBox_UnableChangeSetting {
            get {
                return ResourceManager.GetString("MessageBox_UnableChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINAPI mode is not supported.
        /// </summary>
        internal static string MessageBox_WINAPINotSupported {
            get {
                return ResourceManager.GetString("MessageBox_WINAPINotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Debug folder.
        /// </summary>
        internal static string MsgBox_FailedCreateDebugFolder {
            get {
                return ResourceManager.GetString("MsgBox_FailedCreateDebugFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Folder.
        /// </summary>
        internal static string MsgBox_FolderNotFound {
            get {
                return ResourceManager.GetString("MsgBox_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance has been detected.
        /// </summary>
        internal static string MsgBox_InstanceExists {
            get {
                return ResourceManager.GetString("MsgBox_InstanceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only .ERB files can be dragged and dropped.
        /// </summary>
        internal static string MsgBox_InvalidArg {
            get {
                return ResourceManager.GetString("MsgBox_InvalidArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable &quot;Allow Multiple Instances&quot; config setting if you want to launch multiple instances at once.
        /// </summary>
        internal static string MsgBox_MultiInstanceInfo {
            get {
                return ResourceManager.GetString("MsgBox_MultiInstanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV folder is not found.
        /// </summary>
        internal static string MsgBox_NoCsvFolder {
            get {
                return ResourceManager.GetString("MsgBox_NoCsvFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERB folder is not found.
        /// </summary>
        internal static string MsgBox_NoErbFolder {
            get {
                return ResourceManager.GetString("MsgBox_NoErbFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Emuera in Debug Mode.
        /// </summary>
        internal static string Parameters_HelpDebug {
            get {
                return ResourceManager.GetString("Parameters_HelpDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Era in the given folder.
        /// </summary>
        internal static string Parameters_HelpExeDir {
            get {
                return ResourceManager.GetString("Parameters_HelpExeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to be analyzed.
        /// </summary>
        internal static string Parameters_HelpFilesArg {
            get {
                return ResourceManager.GetString("Parameters_HelpFilesArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart in Debug Mode.
        /// </summary>
        internal static string RestartDebugMode {
            get {
                return ResourceManager.GetString("RestartDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Debug Info.
        /// </summary>
        internal static string UpdateDebugInfo {
            get {
                return ResourceManager.GetString("UpdateDebugInfo", resourceCulture);
            }
        }
    }
}
