//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinorShift.Emuera.UI.Framework {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormLocalization() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinorShift.Emuera.UI.Framework.FormLocalization", typeof(FormLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfigDialog_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Gamepad に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Gamepad {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_Confirm {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_Confirm", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_Cancel {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_Cancel", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_Escape {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_Escape", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_PreviousPage {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_PreviousPage", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_NextPage {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_NextPage", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_Start {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_Start", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_OpenSettings {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_OpenSettings", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_Reset {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_Reset", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_None {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_None", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_FaceSouth {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_FaceSouth", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_FaceEast {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_FaceEast", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_FaceWest {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_FaceWest", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_FaceNorth {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_FaceNorth", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_LeftShoulder {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_LeftShoulder", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_RightShoulder {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_RightShoulder", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_LeftTrigger {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_LeftTrigger", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_RightTrigger {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_RightTrigger", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_StartButton {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_StartButton", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_FixedOperations {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_FixedOperations", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_DPadNavigation {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_DPadNavigation", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_LeftStickNavigation {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_LeftStickNavigation", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_CapturePrompt {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_CapturePrompt", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_CaptureButtonPrompt {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_CaptureButtonPrompt", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_CaptureMultiple {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_CaptureMultiple", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_CaptureCancel {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_CaptureCancel", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_OverrideNote {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_OverrideNote", resourceCulture);
            }
        }

        internal static string ConfigDialog_Gamepad_ApplyImmediately {
            get {
                return ResourceManager.GetString("ConfigDialog_Gamepad_ApplyImmediately", resourceCulture);
            }
        }

        internal static string ConfigDialog_Macro {
            get { return ResourceManager.GetString("ConfigDialog_Macro", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_EditGroup {
            get { return ResourceManager.GetString("ConfigDialog_Macro_EditGroup", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_GamepadTargets {
            get { return ResourceManager.GetString("ConfigDialog_Macro_GamepadTargets", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_Group {
            get { return ResourceManager.GetString("ConfigDialog_Macro_Group", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_Key {
            get { return ResourceManager.GetString("ConfigDialog_Macro_Key", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_Execute1 {
            get { return ResourceManager.GetString("ConfigDialog_Macro_Execute1", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_Execute2 {
            get { return ResourceManager.GetString("ConfigDialog_Macro_Execute2", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_Execute3 {
            get { return ResourceManager.GetString("ConfigDialog_Macro_Execute3", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_Immediate {
            get { return ResourceManager.GetString("ConfigDialog_Macro_Immediate", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_ImmediateOff {
            get { return ResourceManager.GetString("ConfigDialog_Macro_ImmediateOff", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_ImmediateOn {
            get { return ResourceManager.GetString("ConfigDialog_Macro_ImmediateOn", resourceCulture); }
        }

        internal static string ConfigDialog_Macro_ApplyImmediately {
            get { return ResourceManager.GetString("ConfigDialog_Macro_ApplyImmediately", resourceCulture); }
        }
        
        /// <summary>
        ///   ※Changes won&apos;t take effect until restart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_ChangeWontTakeEffectUntilRestart {
            get {
                return ResourceManager.GetString("ConfigDialog_ChangeWontTakeEffectUntilRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check if the file is UTF8 with BOM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_CheckUTF8BOM {
            get {
                return ResourceManager.GetString("ConfigDialog_CheckUTF8BOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AnyKey Wait - When the script waits for any key press に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_AnyKeyWait {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_AnyKeyWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Clipboard and Buffer when game screen clears に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_ClearClipboard {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_ClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double Left Click - Mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_DoubleClick {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore &lt;&gt; tags に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_IgnoreTags {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_IgnoreTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Wait - When the script waits for user input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_InputWait {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_InputWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftClick - Mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_LClick {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_LClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lines to send to Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_LinesToClipboard {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_LinesToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lines to scroll at a time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_LinesToScroll {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_LinesToScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MiddleClick - Mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_MClick {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_MClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show new lines only - Classic Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_NewLineOnly {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_NewLineOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace &lt;&gt; with に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_ReplaceTags {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_ReplaceTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scroll through the history using ctrl+↑ and ↓ or ctrl + mouse wheel up and down. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_ScrollThrough {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_ScrollThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Buffer Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_TotalBuffer {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_TotalBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Triggers to Use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_TriggerToUse {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_TriggerToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min time(mS) between clipboard updates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Clipboard_UpdateTime {
            get {
                return ResourceManager.GetString("ConfigDialog_Clipboard_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compatibility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add TOSTR automatically for user function arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_AutoTOSTR {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_AutoTOSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reproduce non-button wrapping like in pre ver1739 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_ButtonWarp {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_ButtonWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow CALL on event functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_CallEvent {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_CallEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to Emuera default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_EmueraStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EmueraStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Imitate behavior of pseudo-variable RAND from eramaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_EramakerRAND {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EramakerRAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to eramaker default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_EramakerStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EramakerStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calculate TIMES like in eramaker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_EramakerTIMES {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_EramakerTIMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute even if lines cannot be interpreted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_ExecuteErrorLine {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_ExecuteErrorLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use NAME if CALLNAME is empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_NameForCallname {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_NameForCallname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t ignore case for functions and attributes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_NoIgnoreCase {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_NoIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow omission of all arguments when calling user functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_OmitArgs {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_OmitArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow SP characters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_UseSPCharacters {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_UseSPCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※Many things work differently between Emuera and eramaker,
        ///As well as between older and newer Emuera versions,
        ///These options should solve compatibility problems.
        ///Please don&apos;t change anything if there&apos;s no issues. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Compatibility_Warning {
            get {
                return ResourceManager.GetString("ConfigDialog_Compatibility_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display eramaker compatibility warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_CompatibilityWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_CompatibilityWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set for developers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_DeveloperStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_DeveloperStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to deal with calling non-existing functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_FuncNotFoundWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_FuncNotFoundWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore functions that were not called に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_IgnoreUnusedFuncs {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_IgnoreUnusedFuncs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display files that are being loaded at start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_LoadingReport {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_LoadingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set for users に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_PlayerStandard {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_PlayerStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parse arguments when debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs_Always {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Never に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs_Never {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When updated に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_ReduceArgs_OnUpdate {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_ReduceArgs_OnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to deal with never called functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_UnusedFuncWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_UnusedFuncWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum warning level display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0:Non-standard grammar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level0 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1:Possible to ignore errors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level1 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2:Critical errors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level2 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3:Fatal error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnLevel_Level3 {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnLevel_Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show all に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_Always {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore them に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_Ignore {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show only one per file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_OncePerFile {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_OncePerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show only total number of them に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Debug_WarnSetting_TotalNumber {
            get {
                return ResourceManager.GetString("ConfigDialog_Debug_WarnSetting_TotalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Display {
            get {
                return ResourceManager.GetString("ConfigDialog_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t break lines in the middle buttons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Display_ButtonWrap {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_ButtonWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frames per second に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Display_FPS {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of characters in PRINTC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Display_PrintCLength {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_PrintCLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of PRINTC per column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Display_PrintCPerLine {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_PrintCPerLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawing Interface に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Display_TextDrawingMode {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_TextDrawingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the background color of buttons when hovering over it に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Display_UseButtonFocusColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Display_UseButtonFocusColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow multiple instances に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_AllowMultipleInstances {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_AllowMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make autosave に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_AutoSave {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_Browse {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Milliseconds for infinite loop warn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_InfiniteLoopAlertTime {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_InfiniteLoopAlertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lines in history log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_MaxLog {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_MaxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of used save slots に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_SaveDataPerPage {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_SaveDataPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Associated text editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_TextEditor {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command line suffix に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_TextEditorCommandline {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_TextEditorCommandline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_TextEditorCommandline_UserSetting {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_TextEditorCommandline_UserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow debug commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_UseDebugCommand {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseDebugCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use keyboard macros に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_UseKeyMacro {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseKeyMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_UseMenu {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_UseMouse {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use sav folder for save data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Environment_UseSaveFolder {
            get {
                return ResourceManager.GetString("ConfigDialog_Environment_UseSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font {
            get {
                return ResourceManager.GetString("ConfigDialog_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font_BackgroundColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font_FontName {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font_FontSize {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font_HighlightColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_HighlightColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distance between lines に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font_LineHeight {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History Letter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font_LogHistoryColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_LogHistoryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letter Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Font_TextColor {
            get {
                return ResourceManager.GetString("ConfigDialog_Font_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontAntialias に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_FontAntialias {
            get {
                return ResourceManager.GetString("ConfigDialog_FontAntialias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImageSampling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_ImageSampling {
            get {
                return ResourceManager.GetString("ConfigDialog_ImageSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Save {
            get {
                return ResourceManager.GetString("ConfigDialog_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save and Restart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_SaveAndRestart {
            get {
                return ResourceManager.GetString("ConfigDialog_SaveAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System {
            get {
                return ResourceManager.GetString("ConfigDialog_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal language used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_ANSI {
            get {
                return ResourceManager.GetString("ConfigDialog_System_ANSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warn when multiple non-event functions use same name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_DuplicateFuncWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_System_DuplicateFuncWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore capitalization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_IgnoreCase {
            get {
                return ResourceManager.GetString("ConfigDialog_System_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search files in subfolders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_SearchSubfolder {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SearchSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load files in name-order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_SortFileNames {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SortFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow to override system functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_SystemFuncOverride {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SystemFuncOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warn about overridden functions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_SystemFuncOverrideWarn {
            get {
                return ResourceManager.GetString("ConfigDialog_System_SystemFuncOverrideWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use _Rename.csv file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_UseRename {
            get {
                return ResourceManager.GetString("ConfigDialog_System_UseRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use _Replace.csv file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_UseReplace {
            get {
                return ResourceManager.GetString("ConfigDialog_System_UseReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※If you change system settings,
        ///ERB scripts may not work properly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_Warning {
            get {
                return ResourceManager.GetString("ConfigDialog_System_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Include full-width space in whitespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System_WSIncludesFullWidth {
            get {
                return ResourceManager.GetString("ConfigDialog_System_WSIncludesFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System2 {
            get {
                return ResourceManager.GetString("ConfigDialog_System2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t process triple symbols inside FORM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System2_IgnoreTripleSymbol {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_IgnoreTripleSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t autocomplete arguments in character variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System2_NoAutoCompleteCVar {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_NoAutoCompleteCVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use binary format for save data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System2_SaveInBinary {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_SaveInBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use UTF-8 format for save data (only in non-binary) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System2_SaveInUTF8 {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_SaveInUTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use new fast random number algorithm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System2_UseNewRandom {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_UseNewRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable VAR-based instructions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_System2_UseScopedVariableInstruction {
            get {
                return ResourceManager.GetString("ConfigDialog_System2_UseScopedVariableInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Title {
            get {
                return ResourceManager.GetString("ConfigDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window {
            get {
                return ResourceManager.GetString("ConfigDialog_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changeable Window Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_ChangeableWindowHeight {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_ChangeableWindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get present Window Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_GetWindowPos {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_GetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Window Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_GetWindowSize {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_GetWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lines per Scroll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_LinesPerScroll {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_LinesPerScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix starting position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_SetWindowPos {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_SetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last checked Window Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_WindowHeight {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximize window at start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_WindowMaximixed {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowMaximixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_WindowWidth {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed Window Position X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_WindowX {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed Window Position Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigDialog_Window_WindowY {
            get {
                return ResourceManager.GetString("ConfigDialog_Window_WindowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_Cut {
            get {
                return ResourceManager.GetString("ContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_Delete {
            get {
                return ResourceManager.GetString("ContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_Execute {
            get {
                return ResourceManager.GetString("ContextMenu_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_KeyMacro {
            get {
                return ResourceManager.GetString("ContextMenu_KeyMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro Group に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_KeyMacroGroup {
            get {
                return ResourceManager.GetString("ContextMenu_KeyMacroGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_KeyMacroGroup_Group {
            get {
                return ResourceManager.GetString("ContextMenu_KeyMacroGroup_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenu_Paste {
            get {
                return ResourceManager.GetString("ContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Clipboard(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyLogToClipboard {
            get {
                return ResourceManager.GetString("CopyLogToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always show debug window on the foreground に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_AlwaysOnTop {
            get {
                return ResourceManager.GetString("DebugConfigDialog_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_Name {
            get {
                return ResourceManager.GetString("DebugConfigDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show debug window on start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_OpenDebugWindowOnStartup {
            get {
                return ResourceManager.GetString("DebugConfigDialog_OpenDebugWindowOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use current window size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_SetWindowPos {
            get {
                return ResourceManager.GetString("DebugConfigDialog_SetWindowPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ConfigDialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_Title {
            get {
                return ResourceManager.GetString("DebugConfigDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ※These options are related to debug window
        ///Settings apply only at start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_Warning {
            get {
                return ResourceManager.GetString("DebugConfigDialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_WindowHeight {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_WindowWidth {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position in X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_WindowX {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position in Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugConfigDialog_WindowY {
            get {
                return ResourceManager.GetString("DebugConfigDialog_WindowY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_Close {
            get {
                return ResourceManager.GetString("DebugDialog_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_Console {
            get {
                return ResourceManager.GetString("DebugDialog_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load watch list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_File_LoadWatchList {
            get {
                return ResourceManager.GetString("DebugDialog_File_LoadWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save watch list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_File_SaveWatchList {
            get {
                return ResourceManager.GetString("DebugDialog_File_SaveWatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_Setting {
            get {
                return ResourceManager.GetString("DebugDialog_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_Setting_Config {
            get {
                return ResourceManager.GetString("DebugDialog_Setting_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stack Trace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_StackTrace {
            get {
                return ResourceManager.GetString("DebugDialog_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stay On Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_StayOnTop {
            get {
                return ResourceManager.GetString("DebugDialog_StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Emuera - DebugDialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_Title {
            get {
                return ResourceManager.GetString("DebugDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_UpdateData {
            get {
                return ResourceManager.GetString("DebugDialog_UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable Watch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_VariableWatch {
            get {
                return ResourceManager.GetString("DebugDialog_VariableWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_VariableWatch_Object {
            get {
                return ResourceManager.GetString("DebugDialog_VariableWatch_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugDialog_VariableWatch_Value {
            get {
                return ResourceManager.GetString("DebugDialog_VariableWatch_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G{0}:Macro Key F{1}: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyMacro_GMacroKeyF {
            get {
                return ResourceManager.GetString("KeyMacro_GMacroKeyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro Key F{0}: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyMacro_MacroKeyF {
            get {
                return ResourceManager.GetString("KeyMacro_MacroKeyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set to macro group {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KeyMacro_SetMacroGroup {
            get {
                return ResourceManager.GetString("KeyMacro_SetMacroGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to Title Screen(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_BackToTitle {
            get {
                return ResourceManager.GetString("MainWindow_BackToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_CopyToClipboard {
            get {
                return ResourceManager.GetString("MainWindow_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug(&amp;D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Debug {
            get {
                return ResourceManager.GetString("MainWindow_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERB file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_FileFilter {
            get {
                return ResourceManager.GetString("MainWindow_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language(&amp;L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Language {
            get {
                return ResourceManager.GetString("MainWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Debug widow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_OpenDebugWindow {
            get {
                return ResourceManager.GetString("MainWindow_OpenDebugWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Code(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_ReloadAllScripts {
            get {
                return ResourceManager.GetString("MainWindow_ReloadAllScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload Folder(&amp;F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_ReloadFolder {
            get {
                return ResourceManager.GetString("MainWindow_ReloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload File(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_ReloadScriptFile {
            get {
                return ResourceManager.GetString("MainWindow_ReloadScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart(&amp;R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Restart {
            get {
                return ResourceManager.GetString("MainWindow_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save log...(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_SaveLog {
            get {
                return ResourceManager.GetString("MainWindow_SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings(&amp;C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Window Width Lock に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_ToggleWidthLock {
            get {
                return ResourceManager.GetString("MainWindow_ToggleWidthLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainWindow_Tools {
            get {
                return ResourceManager.GetString("MainWindow_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to open the clipboard because of an unexpected error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_CanNotOpenClipboard {
            get {
                return ResourceManager.GetString("MessageBox_CanNotOpenClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot return to title during Analysis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_CanNotReturnToTitle {
            get {
                return ResourceManager.GetString("MessageBox_CanNotReturnToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This function cannot be used when an error occurs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_CanNotUseWhenError {
            get {
                return ResourceManager.GetString("MessageBox_CanNotUseWhenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This function cannot be used during initialization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_CanNotUseWhenInitialize {
            get {
                return ResourceManager.GetString("MessageBox_CanNotUseWhenInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The log file can be saved only in the directory below the executable file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_CanOnlyOutputToSubDirectory {
            get {
                return ResourceManager.GetString("MessageBox_CanOnlyOutputToSubDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Config Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ConfigError {
            get {
                return ResourceManager.GetString("MessageBox_ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a problem with the config file.
        ///Quit Emuera? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ConfigFileError {
            get {
                return ResourceManager.GetString("MessageBox_ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Transfer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_DataTransfer {
            get {
                return ResourceManager.GetString("MessageBox_DataTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Transfer Failure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_DataTransferFailure {
            get {
                return ResourceManager.GetString("MessageBox_DataTransferFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot return to the title due to an error found in Analysis mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ErrorInAnalysisMode {
            get {
                return ResourceManager.GetString("MessageBox_ErrorInAnalysisMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Exit {
            get {
                return ResourceManager.GetString("MessageBox_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit the Game? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ExitAsk {
            get {
                return ResourceManager.GetString("MessageBox_ExitAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create dat folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FailedCreateDataFolder {
            get {
                return ResourceManager.GetString("MessageBox_FailedCreateDataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create sav folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FailedCreateSavFolder {
            get {
                return ResourceManager.GetString("MessageBox_FailedCreateSavFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to move sav files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FailedMoveSavFiles {
            get {
                return ResourceManager.GetString("MessageBox_FailedMoveSavFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log output failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FailedOutputLog {
            get {
                return ResourceManager.GetString("MessageBox_FailedOutputLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log output has been failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FailedOutputLogError {
            get {
                return ResourceManager.GetString("MessageBox_FailedOutputLogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Format Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FileFormatError {
            get {
                return ResourceManager.GetString("MessageBox_FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Not Found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FileNotFound {
            get {
                return ResourceManager.GetString("MessageBox_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Creation Failure に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_FolderCreationFailure {
            get {
                return ResourceManager.GetString("MessageBox_FolderCreationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Illegal Font に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_IllegalFont {
            get {
                return ResourceManager.GetString("MessageBox_IllegalFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An illegal font was detected during the Emuera display processing.
        ///The drawing process cannot continue and will be terminated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_IllegalFontError {
            get {
                return ResourceManager.GetString("MessageBox_IllegalFontError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a possibility of an infinite loop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_InfiniteLoop {
            get {
                return ResourceManager.GetString("MessageBox_InfiniteLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot read files that aren&apos;t .ERB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_IsNotErb {
            get {
                return ResourceManager.GetString("MessageBox_IsNotErb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The line height will be interpreted the same as the font size due to it being smaller. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_LineHeightLessThanFontSize {
            get {
                return ResourceManager.GetString("MessageBox_LineHeightLessThanFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sav folder exists but couldn&apos;t be found.
        ///Was it deleted? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_MissingSavFolder {
            get {
                return ResourceManager.GetString("MessageBox_MissingSavFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some settings couldn&apos;t be changed due to them being fixed by _fixed.config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_NotAllowChangeSetting {
            get {
                return ResourceManager.GetString("MessageBox_NotAllowChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not available during script operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_NotAvailableDuringScript {
            get {
                return ResourceManager.GetString("MessageBox_NotAvailableDuringScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ReloadErb {
            get {
                return ResourceManager.GetString("MessageBox_ReloadErb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try to Load the ERB Files? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ReloadErbAsk {
            get {
                return ResourceManager.GetString("MessageBox_ReloadErbAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Replace.csv Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ReplaceError {
            get {
                return ResourceManager.GetString("MessageBox_ReplaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is a problem with _Replace.csv file.
        ///Quit Emuera? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ReplaceFileError {
            get {
                return ResourceManager.GetString("MessageBox_ReplaceFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_Restart {
            get {
                return ResourceManager.GetString("MessageBox_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart the Game? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_RestartAsk {
            get {
                return ResourceManager.GetString("MessageBox_RestartAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ReturnToTitle {
            get {
                return ResourceManager.GetString("MessageBox_ReturnToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return to Title Screen? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_ReturnToTitleAsk {
            get {
                return ResourceManager.GetString("MessageBox_ReturnToTitleAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sav folder has been created.
        ///Would you like to move the save data there? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_SavFolderCreated {
            get {
                return ResourceManager.GetString("MessageBox_SavFolderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount of save data to display exceeds the limit (More than 80). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_TooLargeDisplaySaveData {
            get {
                return ResourceManager.GetString("MessageBox_TooLargeDisplaySaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currently {1} line at {0} is being executed.
        ///Since the last input {3} milliseconds has passed and the line was executed {2} times.
        ///Would you like to forcibly terminate processing? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_TooLongLoop {
            get {
                return ResourceManager.GetString("MessageBox_TooLongLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amount of save data to display is too small (Less than 20). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_TooSmallDisplaySaveData {
            get {
                return ResourceManager.GetString("MessageBox_TooSmallDisplaySaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font size is too small (Less than 8). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_TooSmallFontSize {
            get {
                return ResourceManager.GetString("MessageBox_TooSmallFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log size is too small (Less than 500). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_TooSmallLogSize {
            get {
                return ResourceManager.GetString("MessageBox_TooSmallLogSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable To Change Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_UnableChangeSetting {
            get {
                return ResourceManager.GetString("MessageBox_UnableChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WINAPI mode is not supported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_WINAPINotSupported {
            get {
                return ResourceManager.GetString("MessageBox_WINAPINotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create Debug folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgBox_FailedCreateDebugFolder {
            get {
                return ResourceManager.GetString("MsgBox_FailedCreateDebugFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgBox_FolderNotFound {
            get {
                return ResourceManager.GetString("MsgBox_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Another instance has been detected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgBox_InstanceExists {
            get {
                return ResourceManager.GetString("MsgBox_InstanceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only .ERB files can be dragged and dropped に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgBox_InvalidArg {
            get {
                return ResourceManager.GetString("MsgBox_InvalidArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable &quot;Allow Multiple Instances&quot; config setting if you want to launch multiple instances at once に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgBox_MultiInstanceInfo {
            get {
                return ResourceManager.GetString("MsgBox_MultiInstanceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV folder is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgBox_NoCsvFolder {
            get {
                return ResourceManager.GetString("MsgBox_NoCsvFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERB folder is not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgBox_NoErbFolder {
            get {
                return ResourceManager.GetString("MsgBox_NoErbFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run Emuera in Debug Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parameters_HelpDebug {
            get {
                return ResourceManager.GetString("Parameters_HelpDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Era in the given folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parameters_HelpExeDir {
            get {
                return ResourceManager.GetString("Parameters_HelpExeDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files to be analyzed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Parameters_HelpFilesArg {
            get {
                return ResourceManager.GetString("Parameters_HelpFilesArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart in Debug Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestartDebugMode {
            get {
                return ResourceManager.GetString("RestartDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Debug Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateDebugInfo {
            get {
                return ResourceManager.GetString("UpdateDebugInfo", resourceCulture);
            }
        }
    }
}
