// Task-only small fixture using the final AOT and unchanged production App UI.
// Reuses the existing native Chrome CDP-pipe harness; no installation/DevTools/throttling.
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';
import {spawn} from 'node:child_process';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
import { verdict } from './verdict.mjs';
const faultMode=process.argv[5]==='fault-selftest';
const root=path.dirname(fileURLToPath(import.meta.url));
const site=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);
if(fs.existsSync(out))throw Error('Refusing evidence overwrite');fs.mkdirSync(out,{recursive:true});
const write=(n,v)=>fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const failures=[],errors=[],network=[],consoleLog=[],httpLog=[],rows=[],responses=[];
const fixture=path.resolve(process.argv[4]??path.join(root,'fixture/package'));
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.wasm':'application/wasm','.json':'application/json','.png':'image/png','.zip':'application/zip'};
const server=http.createServer((req,res)=>{
 if(faultMode && req.url.startsWith('/__intentional/')) { const action=req.url.split('/').at(-1); if(action==='disconnect'){req.socket.destroy();return;} const status=action==='500'?500:404;httpLog.push({path:req.url,status,intentional:true});res.writeHead(status).end('intentional runner verdict self-test');return;}
 const u=new URL(req.url,'http://localhost'),base=u.pathname.startsWith('/p1b-data/')?fixture:site;
 const rel=base===fixture?u.pathname.slice('/p1b-data/'.length):u.pathname==='/'?'index.html':u.pathname.slice(1);
 const f=path.resolve(base,decodeURIComponent(rel));
 if(u.pathname==='/favicon.ico'){res.writeHead(204).end();return;}
 if(!f.startsWith(base+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){httpLog.push({path:u.pathname,status:404});res.writeHead(404).end();return;}
 httpLog.push({path:u.pathname,status:200,bytes:fs.statSync(f).size});res.setHeader('content-type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}/?fixture=p1c3-real&profile=getkey-isolated-fixture`;
const binary=process.env.CHROME_BINARY || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const flags=['--headless=new','--enable-automation','--disable-background-networking','--disable-extensions','--no-first-run','--no-default-browser-check','--window-size=1920,1080',`--user-data-dir=${path.join(out,'profile')}`,'--remote-debugging-pipe','about:blank'];
const chrome=spawn(binary,flags,{windowsHide:true,stdio:['ignore','ignore','pipe','pipe','pipe']});
chrome.stderr.pipe(fs.createWriteStream(path.join(out,'chrome-stderr.log')));
let session='',seq=0,buffer=Buffer.alloc(0);const pending=new Map();
chrome.on('exit',(code,signal)=>{for(const p of pending.values())p.reject(Error(`Task Chrome exited: ${code}/${signal}`));pending.clear();});
function call(method,params={},s=session){if(chrome.exitCode!==null)return Promise.reject(Error(`Task Chrome exited: ${chrome.exitCode}`));return new Promise((resolve,reject)=>{const id=++seq,t=setTimeout(()=>{pending.delete(id);reject(Error(method+' timeout'))},60000);pending.set(id,{resolve:r=>{clearTimeout(t);resolve(r)},reject:e=>{clearTimeout(t);reject(e)}});chrome.stdio[3].write(JSON.stringify({id,method,params,...(s?{sessionId:s}:{})})+'\0')});}
chrome.stdio[4].on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);while(buffer.indexOf(0)>=0){const n=buffer.indexOf(0),m=JSON.parse(buffer.subarray(0,n).toString());buffer=buffer.subarray(n+1);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown'||m.method==='Log.entryAdded'&&m.params.entry.level==='error'||m.method==='Runtime.consoleAPICalled'&&m.params.type==='error'){errors.push(m);}else if(m.method==='Runtime.consoleAPICalled'){consoleLog.push({type:m.params.type,args:m.params.args.map(a=>a.value??a.description)});}else if(m.method==='Network.loadingFailed'){network.push(m.params);}else if(m.method==='Network.responseReceived'){responses.push({url:m.params.response.url,status:m.params.response.status});}}});
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
function check(ok,label){if(!ok)failures.push(label);}
async function waitFor(expression,label,limit=12000){const end=Date.now()+limit;while(Date.now()<end){if(errors.length)throw Error('Runtime/console error during '+label);if(await evaluate(expression))return;if(errors.length)throw Error('Runtime/console error during '+label);await sleep(100);}throw Error('timeout '+label);}
const status=()=>evaluate("({status:{...document.querySelector('#p1c2-status').dataset},text:document.querySelector('#game-screen').textContent,island:document.querySelector('#game-island-layer')?.textContent})");
async function screenshot(name){fs.writeFileSync(path.join(out,name+'.png'),Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));}
try{
 const version=await call('Browser.getVersion',{},'');const t=await call('Target.createTarget',{url:'about:blank'},'');session=(await call('Target.attachToTarget',{targetId:t.targetId,flatten:true},'')).sessionId;
 for(const d of ['Page','Runtime','Network','Log'])await call(d+'.enable');
 await call('Emulation.setDeviceMetricsOverride',{width:1920,height:1080,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url});
 await waitFor("document.querySelector('#game-screen')?.textContent.includes('GETKEY_FIXTURE') && document.querySelector('#p1c2-status')?.dataset.pendingKind==='integer'",'GETKEY fixture',60000);
 await evaluate("window.getkeyFocusTrace=[];document.addEventListener('focusout',e=>window.getkeyFocusTrace.push({type:'focusout',target:e.target.id||e.target.className,related:e.relatedTarget?.id||e.relatedTarget?.className||null,active:document.activeElement?.id||document.activeElement?.tagName,focused:document.hasFocus()}),true)");
 await evaluate("window.getkeyEvents=[];for(const type of ['keydown','keyup','compositionstart','compositionend'])document.addEventListener(type,e=>{if(window.getkeyEvents.length<2000)window.getkeyEvents.push({type:e.type,code:e.code,key:e.key,keyCode:e.keyCode,isComposing:e.isComposing,repeat:e.repeat,isTrusted:e.isTrusted,time:performance.now(),target:e.target.id})},true)");
 async function kd(code,vk,mods=0){await call('Input.dispatchKeyEvent',{type:'keyDown',code,key:code.startsWith('Alt')?'Alt':code.startsWith('Shift')?'Shift':code.startsWith('Control')?'Control':code==='KeyA'?'a':code,windowsVirtualKeyCode:vk,modifiers:mods});}
 async function ku(code,vk,mods=0){await call('Input.dispatchKeyEvent',{type:'keyUp',code,key:code.startsWith('Alt')?'Alt':code.startsWith('Shift')?'Shift':code.startsWith('Control')?'Control':code==='KeyA'?'a':code,windowsVirtualKeyCode:vk,modifiers:mods});}
 async function query(name,expected,mods=0,buttons=0){const before=Number([...(await status()).text.matchAll(/QID=(\d+)/g)].at(-1)?.[1]??0);const pos=await evaluate("(()=>{const e=Array.from(document.querySelectorAll('#game-screen .game-button')).filter(e=>e.textContent.includes('QUERY')).at(-1);const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()");await call('Input.dispatchMouseEvent',{type:'mouseMoved',...pos,buttons,modifiers:mods});await call('Input.dispatchMouseEvent',{type:'mousePressed',...pos,button:'left',buttons:buttons|1,clickCount:1,modifiers:mods});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...pos,button:'left',buttons,clickCount:1,modifiers:mods});await waitFor("Number([...document.querySelector('#game-screen').textContent.matchAll(/QID=(\\d+)/g)].at(-1)?.[1]??0)>"+JSON.stringify(before)+" && document.querySelector('#p1c2-status').dataset.pendingKind==='integer'",'query accepted');const st=await status();const found=[...st.text.matchAll(/KEYS=([01](?:,[01]){16})/g)];assert.ok(found.length,'GETKEY output');const values=found.at(-1)[1].split(',').map(Number);const repeated=[...st.text.matchAll(/REPEAT=([01],[01],[01])/g)].at(-1)?.[1].split(',').map(Number);assert.deepEqual(repeated,[values[0],values[3],values[14]],'same ERB batch repeated queries must not consume state');const nc=[...st.text.matchAll(/NCREPEAT=([01],[01])/g)].at(-1)?.[1].split(',').map(Number);assert.deepEqual(nc,[values[15],values[15]],'NonConvert is non-consuming');const dash=[...st.text.matchAll(/DASHMODES=([01],[01],[01])/g)].at(-1)?.[1].split(',').map(Number);const modifier=values[0]||values[3]||values[15];assert.deepEqual(dash,[0,modifier?1:0,modifier?0:1],'dash mode branch predicates');const okay=Object.entries(expected).every(([i,v])=>values[Number(i)]===v);rows.push({name,expected,actual:values,repeated,nc,dash,pass:okay,request:st.status.requestId});write('checks.json',rows);}
 await evaluate("document.querySelector('#runtime-input').focus()");await kd('AltLeft',18,1);await query('Alt from ordinary input field + click',{0:1,1:1,2:0},1);await ku('AltLeft',18);await query('released Alt',{0:0,1:0,2:0});
 await evaluate("document.querySelector('#game-screen').focus()");await kd('AltRight',18,1);await query('right Alt',{0:1,1:0,2:1},1);await kd('AltLeft',18,1);await query('both Alt',{0:1,1:1,2:1},1);await ku('AltLeft',18,1);await query('release left while right held',{0:1,1:0,2:1},1);await ku('AltRight',18);await query('both released',{0:0,1:0,2:0});
 await evaluate("document.querySelector('#runtime-input').focus()");await kd('KeyA',65);await query('A held from ordinary input',{14:1});await query('repeat query does not consume key',{14:1});await ku('KeyA',65);await query('A released',{14:0});await kd('KeyA',65);await ku('KeyA',65);await query('short released press is not a pulse',{14:0});
 if(process.argv[5]!=='before'){
  await evaluate("document.querySelector('#runtime-input').focus()");await kd('KeyA',65);await evaluate("document.querySelector('#game-screen').focus()");await query('input to game focus keeps actual held A',{14:1});await ku('KeyA',65);
  await kd('ShiftLeft',16,8);await kd('ShiftRight',16,8);await query('both Shift',{8:1,9:1,10:1},8);await ku('ShiftLeft',16,8);await query('right Shift after left release',{8:1,9:0,10:1},8);await ku('ShiftRight',16);
  await kd('ControlLeft',17,2);await kd('ControlRight',17,2);await query('both Control',{11:1,12:1,13:1},2);await ku('ControlLeft',17,2);await query('right Control after left release',{11:1,12:0,13:1},2);await ku('ControlRight',17);
  await kd('AltLeft',18,1);await kd('KeyA',65,1);await query('simultaneous Alt and A',{0:1,1:1,14:1},1);await ku('KeyA',65,1);await ku('AltLeft',18);
  const p={x:40,y:90};await call('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'right',buttons:2,clickCount:1});await query('right mouse held during ordinary button input',{6:1,7:0},0,2);await call('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'right',buttons:0,clickCount:1});await query('right mouse released',{6:0});
  await call('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'middle',buttons:4,clickCount:1});await query('middle mouse held during ordinary button input',{7:1},0,4);await call('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'middle',buttons:0,clickCount:1});await query('middle mouse released',{7:0});
  await kd('KeyA',65);const t2=await call('Target.createTarget',{url:'about:blank'},'');const s2=(await call('Target.attachToTarget',{targetId:t2.targetId,flatten:true},'')).sessionId;await call('Page.bringToFront',{},s2);
  await waitFor("!document.hasFocus() || document.hidden",'actual tab focus loss');
  assert.equal(await evaluate("import('./host-key-macros.js').then(m=>m.getKeyState(65))"),0,'inactive page state zero');
  await call('Page.bringToFront');await call('Target.closeTarget',{targetId:t2.targetId},'');await waitFor('document.hasFocus() && !document.hidden','return focus');await evaluate("document.querySelector('#game-screen').focus()");await query('tab loss and refocus cannot retain A',{14:0});
  await call('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyA',key:'a',windowsVirtualKeyCode:65,autoRepeat:true});await query('repeat after tab return cannot resurrect held A',{14:0});await ku('KeyA',65);await kd('KeyA',65);await query('new A press after tab return',{14:1});await ku('KeyA',65);
 }
 // These VK numbers are deliberately specified by CDP: not hardware mapping evidence.
 await evaluate("document.querySelector('#runtime-input').focus()");await kd('NonConvert',29);await query('NonConvert CDP VK29 held',{15:1});await query('NonConvert CDP VK29 repeated query',{15:1});await ku('NonConvert',29);await query('NonConvert CDP VK29 released',{15:0});await kd('NonConvert',29);await ku('NonConvert',29);await query('NonConvert released short press',{15:0});
 await kd('Escape',27);await query('Escape CDP VK27 held',{16:1});await ku('Escape',27);await query('Escape released',{16:0});
 await kd('NonConvert',29);await evaluate("document.querySelector('#runtime-input').dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:'あ'}))");await query('composition start clears NonConvert',{15:0});
 await evaluate("document.querySelector('#runtime-input').dispatchEvent(new KeyboardEvent('keydown',{bubbles:true,code:'NonConvert',key:'NonConvert',keyCode:29,isComposing:true}))");await query('isComposing NonConvert ignored',{15:0});
 await evaluate("document.querySelector('#runtime-input').dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'あ'}));document.querySelector('#runtime-input').dispatchEvent(new KeyboardEvent('keydown',{bubbles:true,code:'NonConvert',key:'Process',keyCode:229}))");await query('keyCode229 ignored',{15:0});await ku('NonConvert',29);
 await kd('NonConvert',29);await query('fresh NonConvert after composition',{15:1});await ku('NonConvert',29);
 const p={x:40,y:90};await call('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'back',buttons:8,clickCount:1});await query('XBUTTON1 held with left click',{3:1,4:0},0,8);// Keep back held until the task browser closes: releasing it invokes browser Back; synthetic release/mapping is covered separately and physical side buttons remain a browser constraint.
 await screenshot('getkey-fixture-final');write('focus-trace.json',await evaluate('window.getkeyFocusTrace'));write('checks.json',rows);write('errors.json',{errors,network,consoleLog});write('http.json',httpLog);write('environment.json',{version,binary,flags,site,url,fixture,scope:'CDP events delivered to actual browser and real ERB GETKEY; hardware browser-reserved buttons not guaranteed'});
 write('browser-events.json',{provenance:'CDP VK injection and synthetic composition; isTrusted is not proof of physical hardware origin',events:await evaluate('window.getkeyEvents')});
 const clean=verdict({checks:rows,errors,network,http:[...httpLog,...responses],failures,complete:true});assert.equal(clean.status,'PASS',JSON.stringify(clean));
 if(faultMode){
   await evaluate("(async()=>{console.error('INTENTIONAL_VERDICT_CONSOLE_ERROR');setTimeout(()=>{throw Error('INTENTIONAL_VERDICT_RUNTIME_EXCEPTION')},0);await Promise.allSettled([fetch('/__intentional/404'),fetch('/__intentional/500'),fetch('/__intentional/disconnect')]);await new Promise(r=>setTimeout(r,100))})()");
   const rejected=verdict({checks:rows,errors,network,http:[...httpLog,...responses],failures,complete:true});
   assert.equal(rejected.status,'FAIL');assert.ok(errors.some(e=>e.method==='Runtime.consoleAPICalled'));assert.ok(errors.some(e=>e.method==='Runtime.exceptionThrown'));assert.ok(network.length);assert.ok(httpLog.some(e=>e.status===404));assert.ok(httpLog.some(e=>e.status===500));
   write('errors.json',{intentionalFaultPhase:true,errors,network,consoleLog});write('http.json',httpLog);write('result.json',{...rejected,testStatus:'PASS_EXPECTED_REJECTION',cleanPhase:clean,intentionalFaults:['console error','uncaught runtime exception','HTTP404','HTTP500','connection termination']});console.log(JSON.stringify({testStatus:'PASS_EXPECTED_REJECTION',verdict:rejected}));
 }else{
 const mismatches=rows.filter(r=>!r.pass);const beforeMode=process.argv[5]==='before';write('result.json',{...verdict({checks:rows,errors,network,http:[...httpLog,...responses],failures,complete:true}),legacyStatus:beforeMode?(mismatches.length?'REPRODUCED_NATIVE_DIFFERENCES':'NO_REPRODUCTION'):(mismatches.length?'FAIL':'PASS'),checks:rows.length,mismatches:mismatches.length,errors:errors.length,network:network.length});console.log(JSON.stringify({before:beforeMode,checks:rows.length,mismatches:mismatches.map(x=>x.name),errors}));if(!beforeMode){assert.deepEqual(mismatches,[]);assert.equal(verdict({checks:rows,errors,network,http:[...httpLog,...responses],failures,complete:true}).status,'PASS');}
 }
}catch(e){failures.push(e.stack);write('checks.json',rows);write('errors.json',{errors,network,consoleLog});write('http.json',httpLog);write('result.json',verdict({checks:rows,errors,network,http:[...httpLog,...responses],failures,complete:false}));write('failure.json',{message:e.stack,failures,errors,network,httpLog});try{write('failure-dom.json',await status());await screenshot('failure');}catch{}process.exitCode=1;console.error(e);}finally{
 if(chrome.exitCode===null){await Promise.race([call('Browser.close',{},'').catch(()=>{}),sleep(5000)]);if(chrome.exitCode===null)chrome.kill();}server.closeAllConnections();await new Promise(r=>server.close(r));
}
